
/*
The following material is a "digital artifact" containing a series of complete
or partial SQL "schema definition" and/or "schema manipulation" statements
that effectively create or modify an SQL schema to support the facilities defined in one
part of ISO/IEC 9075. 

These statements may be used by SQL-implementations to create their initial
Information and Definition schemata. 
*/

      
      
/* Definition Schema */
      
INSERT INTO DATA_TYPES_LIST ( DATA_TYPE  )
    VALUES ('XML');

  
INSERT INTO USAGE_OBJECT_TYPES_LIST ( OBJECT_TYPE )
    VALUES ('XML SCHEMA');

  
ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN XML_PRIMARY_MODIFIER          INFORMATION_SCHEMA.CHARACTER_DATA
        CONSTRAINT DATA_TYPE_DESCRIPTOR_XML_PRIMARY_MODIFIER_CHECK
             CHECK ( XML_PRIMARY_MODIFIER IN ( 'DOCUMENT', 'CONTENT', 'SEQUENCE' ) );

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN XML_SECONDARY_MODIFIER        INFORMATION_SCHEMA.CHARACTER_DATA
        CONSTRAINT DATA_TYPE_DESCRIPTOR_XML_SECONDARY_MODIFIER_CHECK
             CHECK ( XML_SECONDARY_MODIFIER IN ( 'UNTYPED', 'ANY', 'XMLSCHEMA' ) );

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN XML_SCHEMA_CATALOG            INFORMATION_SCHEMA.SQL_IDENTIFIER;

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN XML_SCHEMA_SCHEMA             INFORMATION_SCHEMA.SQL_IDENTIFIER;

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN XML_SCHEMA_NAME               INFORMATION_SCHEMA.SQL_IDENTIFIER;

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN XML_SCHEMA_NAMESPACE          INFORMATION_SCHEMA.URI;

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN XML_SCHEMA_ELEMENT            INFORMATION_SCHEMA.NCNAME;

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD CONSTRAINT DATA_TYPE_DESCRIPTOR_DATA_TYPE_CHECK_XML
       CHECK ( ( DATA_TYPE = 'XML'
              AND
                XML_PRIMARY_MODIFIER IS NOT NULL
              AND
                ( XML_PRIMARY_MODIFIER NOT IN ( 'DOCUMENT', 'CONTENT' )
                OR
                  XML_SECONDARY_MODIFIER IS NOT NULL )
              AND
                  ( XML_SECONDARY_MODIFIER <> 'XMLSCHEMA'
                  OR
                    ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA, XML_SCHEMA_NAME ) IS NULL ) )
              OR
               DATA_TYPE <> 'XML' );

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD CONSTRAINT DATA_TYPE_DESCRIPTOR_DATA_TYPE_CHECK_NOT_XML
      CHECK ( DATA_TYPE <> 'XML'
              AND
            ( XML_PRIMARY_MODIFIER, XML_SECONDARY_MODIFIER, XML_SCHEMA_CATALOG, 
              XML_SCHEMA_SCHEMA, XML_SCHEMA_NAME, XML_SCHEMA_NAMESPACE, 
              XML_SCHEMA_ELEMENT ) IS NULL );

ALTER TABLE DATA_TYPE_DESCRIPTOR 
    ADD CONSTRAINT DATA_TYPE_DESCRIPTOR_CHECK_REFERENCES_XML_SCHEMA_NAMESPACES
      CHECK ( XML_SCHEMA_CATALOG NOT IN
              ( SELECT CATALOG_NAME
                FROM SCHEMATA )
           OR
            ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA, XML_SCHEMA_NAME,
              XML_SCHEMA_NAMESPACE) IN
              ( SELECT XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA,
                       XML_SCHEMA_NAME, XML_SCHEMA_NAMESPACE
                FROM XML_SCHEMA_NAMESPACES ) );
             
ALTER TABLE DATA_TYPE_DESCRIPTOR 
    ADD CONSTRAINT DATA_TYPE_DESCRIPTOR_CHECK_REFERENCES_XML_SCHEMA_ELEMENTS
      CHECK ( XML_SCHEMA_CATALOG NOT IN
              ( SELECT CATALOG_NAME
                FROM SCHEMATA )
           OR
            ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA, XML_SCHEMA_NAME,
              XML_SCHEMA_NAMESPACE, XML_SCHEMA_ELEMENT) IN
              ( SELECT XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA,
                       XML_SCHEMA_NAME, XML_SCHEMA_NAMESPACE,
                       XML_SCHEMA_ELEMENT
                FROM XML_SCHEMA_ELEMENTS ) );

  
ALTER TABLE PARAMETERS
    ADD COLUMN XML_STRING_DTD_IDENTIFIER        INFORMATION_SCHEMA.SQL_IDENTIFIER;

ALTER TABLE PARAMETERS
    ADD COLUMN XML_OPTION                       INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT XML_OPTION_CHECK
        CHECK (XML_OPTION IN ( 'CONTENT', 'DOCUMENT' ) );

ALTER TABLE PARAMETERS
    ADD COLUMN XML_PASSING_MECHANISM            INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT XML_PASSING_MECHANISM_CHECK
        CHECK (XML_PASSING_MECHANISM IN
          ( 'BY REF', 'BY VALUE' ) );

ALTER TABLE PARAMETERS ADD
    CONSTRAINT PARAMETERS_CHECK_XML_DATA_TYPE
      CHECK (
        ( SPECIFIC_CATALOG, SPECIFIC_SCHEMA,
          SPECIFIC_NAME, 'ROUTINE', XML_STRING_DTD_IDENTIFIER ) IN
          ( SELECT OBJECT_CATALOG, OBJECT_SCHEMA,
                   OBJECT_NAME, OBJECT_TYPE, DTD_IDENTIFIER
            FROM DATA_TYPE_DESCRIPTOR ) );

  
ALTER TABLE ROUTINES 
    ADD COLUMN XML_STRING_DTD_IDENTIFIER         INFORMATION_SCHEMA.SQL_IDENTIFIER;

ALTER TABLE ROUTINES 
    ADD COLUMN XML_OPTION                        INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT XML_OPTION_CHECK
        CHECK (XML_OPTION IN ( 'CONTENT', 'DOCUMENT' ) );

ALTER TABLE ROUTINES 
    ADD COLUMN XML_RETURN_MECHANISM              INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT XML_RETURN_MECHANISM_CHECK
        CHECK (XML_RETURN_MECHANISM IN
          ( 'BY REF', 'BY VALUE' ) );

ALTER TABLE ROUTINES
    ADD CONSTRAINT ROUTINES_CHECK_XML_STRING_DTD_IDENTIFIER
        CHECK (
          ( SPECIFIC_CATALOG, SPECIFIC_SCHEMA, SPECIFIC_NAME,
            'ROUTINE', XML_STRING_DTD_IDENTIFIER ) IN
            ( SELECT OBJECT_CATALOG, OBJECT_SCHEMA, OBJECT_NAME,
                     OBJECT_TYPE, DTD_IDENTIFIER
              FROM DATA_TYPE_DESCRIPTOR ) );

  
CREATE TABLE XML_SCHEMA_ELEMENTS (
    XML_SCHEMA_CATALOG                           INFORMATION_SCHEMA.SQL_IDENTIFIER,
    XML_SCHEMA_SCHEMA                            INFORMATION_SCHEMA.SQL_IDENTIFIER,
    XML_SCHEMA_NAME                              INFORMATION_SCHEMA.SQL_IDENTIFIER,
    XML_SCHEMA_NAMESPACE                         INFORMATION_SCHEMA.URI,
    XML_SCHEMA_ELEMENT                           INFORMATION_SCHEMA.NCNAME,
    XML_SCHEMA_ELEMENT_IS_DETERMINISTIC          INFORMATION_SCHEMA.YES_OR_NO
      CONSTRAINT XML_SCHEMA_ELEMENT_IS_DETERMINISTIC_NOT_NULL
        NOT NULL,

    CONSTRAINT XML_SCHEMA_ELEMENTS_PRIMARY_KEY
      PRIMARY KEY ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA,
                    XML_SCHEMA_NAME, XML_SCHEMA_NAMESPACE,
                    XML_SCHEMA_ELEMENT ),

    CONSTRAINT XML_SCHEMA_ELEMENTS_FOREIGN_KEY_XML_SCHEMA_NAMESPACES
      FOREIGN KEY ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA,
                    XML_SCHEMA_NAME, XML_SCHEMA_NAMESPACE )
      REFERENCES XML_SCHEMA_NAMESPACES
    );

  
CREATE TABLE XML_SCHEMA_NAMESPACES (
    XML_SCHEMA_CATALOG                           INFORMATION_SCHEMA.SQL_IDENTIFIER,
    XML_SCHEMA_SCHEMA                            INFORMATION_SCHEMA.SQL_IDENTIFIER,
    XML_SCHEMA_NAME                              INFORMATION_SCHEMA.SQL_IDENTIFIER,
    XML_SCHEMA_NAMESPACE                         INFORMATION_SCHEMA.URI,
    XML_SCHEMA_NAMESPACE_IS_DETERMINISTIC        INFORMATION_SCHEMA.YES_OR_NO
    CONSTRAINT XML_SCHEMA_NAMESPACE_IS_DETERMINISTIC_NOT_NULL
      NOT NULL,

    CONSTRAINT XML_SCHEMA_NAMESPACES_PRIMARY_KEY
      PRIMARY KEY ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA,
                    XML_SCHEMA_NAME, XML_SCHEMA_NAMESPACE ),

    CONSTRAINT XML_SCHEMA_NAMESPACES_FOREIGN_KEY_XML_SCHEMAS
      FOREIGN KEY ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA,
                    XML_SCHEMA_NAME )
        REFERENCES XML_SCHEMAS
    );

  
CREATE TABLE XML_SCHEMAS (
    XML_SCHEMA_TARGET_NAMESPACE                  INFORMATION_SCHEMA.URI
      CONSTRAINT XML_SCHEMA_TARGET_NAMESPACE_NOT_NULL
        NOT NULL,
    XML_SCHEMA_LOCATION                          INFORMATION_SCHEMA.URI
      CONSTRAINT XML_SCHEMA_LOCATION_NOT_NULL
        NOT NULL,
    XML_SCHEMA_CATALOG                           INFORMATION_SCHEMA.SQL_IDENTIFIER,
    XML_SCHEMA_SCHEMA                            INFORMATION_SCHEMA.SQL_IDENTIFIER,
    XML_SCHEMA_NAME                              INFORMATION_SCHEMA.SQL_IDENTIFIER,
    XML_SCHEMA_IS_DETERMINISTIC                  INFORMATION_SCHEMA.YES_OR_NO
      CONSTRAINT XML_SCHEMA_IS_DETERMINISTIC_NOT_NULL
        NOT NULL,
    XML_SCHEMA_IS_PERMANENT                      INFORMATION_SCHEMA.YES_OR_NO
      CONSTRAINT XML_SCHEMA_IS_PERMANENT_NOT_NULL
        NOT NULL,

    CONSTRAINT XML_SCHEMAS_PRIMARY_KEY
      PRIMARY KEY ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA, XML_SCHEMA_NAME ),

    CONSTRAINT XML_SCHEMA_FOREIGN_KEY_XML_SCHEMA_NAMESPACES
      FOREIGN KEY ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA,
                    XML_SCHEMA_NAME, XML_SCHEMA_TARGET_NAMESPACE )
        REFERENCES XML_SCHEMA_NAMESPACES,

    CONSTRAINT XML_SCHEMA_FOREIGN_KEY_XML_SCHEMATA
      FOREIGN KEY ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA )
        REFERENCES SCHEMATA
    );

  
      
      
/* Information Schema */      
      
CREATE DOMAIN NCNAME AS
  CHARACTER VARYING(L)
    CHARACTER SET CS;
GRANT USAGE ON NCNAME
    TO PUBLIC WITH GRANT OPTION;

  
CREATE DOMAIN URI AS
  CHARACTER VARYING(L)
    CHARACTER SET CS;
GRANT USAGE ON URI
    TO PUBLIC WITH GRANT OPTION;

  
/* Modify the ATTRIBUTES view by inserting after the text:
     
        DECLARED_DATA_TYPE, DECLARED_NUMERIC_PRECISION,
        DECLARED_NUMERIC_SCALE

   the text:
     
,
D1.XML_PRIMARY_MODIFIER, D1.XML_SECONDARY_MODIFIER,
D1.XML_SCHEMA_CATALOG, D1.XML_SCHEMA_SCHEMA, D1.XML_SCHEMA_NAME,
D1.XML_SCHEMA_NAMESPACE, D1.XML_SCHEMA_ELEMENT

*/
    
  
/* Modify the COLUMNS view by inserting after the text:
     
      COALESCE (D1.DECLARED_NUMERIC_PRECISION, D2.DECLARED_NUMERIC_PRECISION)
               AS DECLARED_NUMERIC_PRECISION,
      COALESCE (D1.DECLARED_NUMERIC_SCALE, D2.DECLARED_NUMERIC_SCALE)
               AS DECLARED_NUMERIC_SCALE

   the text:
     
,
COALESCE (D1.XML_PRIMARY_MODIFIER, D2.XML_PRIMARY_MODIFIER) AS
         XML_PRIMARY_MODIFIER,
COALESCE (D1.XML_SECONDARY_MODIFIER, D2.XML_SECONDARY_MODIFIER) AS
         XML_SECONDARY_MODIFIER,
COALESCE (D1.XML_SCHEMA_CATALOG, D2.XML_SCHEMA_CATALOG) AS
         XML_SCHEMA_CATALOG,
COALESCE (D1.XML_SCHEMA_SCHEMA, D2.XML_SCHEMA_SCHEMA) AS
         XML_SCHEMA_SCHEMA,
COALESCE (D1.XML_SCHEMA_NAME, D2.XML_SCHEMA_NAME) AS
         XML_SCHEMA_NAME,
COALESCE (D1.XML_SCHEMA_NAMESPACE, D2.XML_SCHEMA_NAMESPACE) AS
         XML_SCHEMA_NAMESPACE,
COALESCE (D1.XML_SCHEMA_ELEMENT, D2.XML_SCHEMA_ELEMENT) AS
         XML_SCHEMA_ELEMENT

*/
    
  
/* Modify the DOMAINS view by inserting after the text:
     
      DTD.DECLARED_DATA_TYPE, DTD.DECLARED_NUMERIC_PRECISION,
      DTD.DECLARED_NUMERIC_SCALE

   the text:
     
,
DTD.XML_PRIMARY_MODIFIER, DTD.XML_SECONDARY_MODIFIER,
DTD.XML_SCHEMA_CATALOG, DTD.XML_SCHEMA_SCHEMA, DTD.XML_SCHEMA_NAME,
DTD.XML_SCHEMA_NAMESPACE, DTD.XML_SCHEMA_ELEMENT

*/
    
  
/* Modify the ELEMENT_TYPES view by inserting after the text:
     
        DTD.DECLARED_DATA_TYPE, DTD.DECLARED_NUMERIC_PRECISION,
        DTD.DECLARED_NUMERIC_SCALE

   the text:
     
,
DTD.XML_PRIMARY_MODIFIER, DTD.XML_SECONDARY_MODIFIER,
DTD.XML_SCHEMA_CATALOG, DTD.XML_SCHEMA_SCHEMA, DTD.XML_SCHEMA_NAME,
DTD.XML_SCHEMA_NAMESPACE, DTD.XML_SCHEMA_ELEMENT

*/
    
  
/* Modify the FIELDS view by inserting after the text:
     
        DTD.DECLARED_DATA_TYPE, DTD.DECLARED_NUMERIC_PRECISION,
        DTD.DECLARED_NUMERIC_SCALE

   the text:
     
,
DTD.XML_PRIMARY_MODIFIER, DTD.XML_SECONDARY_MODIFIER,
DTD.XML_SCHEMA_CATALOG, DTD.XML_SCHEMA_SCHEMA, DTD.XML_SCHEMA_NAME,
DTD.XML_SCHEMA_NAMESPACE, DTD.XML_SCHEMA_ELEMENT

*/
    
  
/* Modify the METHOD_SPECIFICATION_PARAMETERS view by inserting after the text:
     
           D.DECLARED_DATA_TYPE, D.DECLARED_NUMERIC_PRECISION,
           D.DECLARED_NUMERIC_SCALE

   the text:
     
,
D.XML_PRIMARY_MODIFIER, D.XML_SECONDARY_MODIFIER,
D.XML_SCHEMA_CATALOG, D.XML_SCHEMA_SCHEMA, D.XML_SCHEMA_NAME,
D.XML_SCHEMA_NAMESPACE, D.XML_SCHEMA_ELEMENT

*/
    
  
/* Modify the METHOD_SPECIFICATIONS view by inserting after the text:
     
           D.DECLARED_DATA_TYPE, D.DECLARED_NUMERIC_PRECISION,
           D.DECLARED_NUMERIC_SCALE

   the text:
     
,
D.XML_PRIMARY_MODIFIER, D.XML_SECONDARY_MODIFIER,
D.XML_SCHEMA_CATALOG, D.XML_SCHEMA_SCHEMA, D.XML_SCHEMA_NAME,
D.XML_SCHEMA_NAMESPACE, D.XML_SCHEMA_ELEMENT,
DT.XML_PRIMARY_MODIFIER AS RESULT_CAST_XML_PRIMARY_MODIFIER,
DT.XML_SECONDARY_MODIFIER AS RESULT_CAST_XML_SECONDARY_MODIFIER,
DT.XML_SCHEMA_CATALOG AS RESULT_CAST_XML_SCHEMA_CATALOG,
DT.XML_SCHEMA_SCHEMA AS RESULT_CAST_XML_SCHEMA_SCHEMA,
DT.XML_SCHEMA_NAME AS RESULT_CAST_XML_SCHEMA_NAME,
DT.XML_SCHEMA_NAMESPACE AS RESULT_CAST_XML_SCHEMA_NAMESPACE,
DT.XML_SCHEMA_ELEMENT AS RESULT_CAST_XML_SCHEMA_ELEMENT

*/
    
  
/* Modify the PARAMETERS view by inserting after the text:
     
           END AS PARAMETER_DEFAULT,
           DTD.TABLE_SEMANTICS, DTD.IS_PRUNABLE, DTD.HAS_PASS_THROUGH_COLUMNS

   the text:
     
      ,
      DTD.XML_PRIMARY_MODIFIER, DTD.XML_SECONDARY_MODIFIER,
      DTD.XML_SCHEMA_CATALOG, DTD.XML_SCHEMA_SCHEMA, DTD.XML_SCHEMA_NAME,
      DTD.XML_SCHEMA_NAMESPACE, DTD.XML_SCHEMA_ELEMENT,
      DTD2.DATA_TYPE AS XML_CHAR_TYPE,
      DTD2.CHARACTER_MAXIMUM_LENGTH AS XML_CHAR_MAX_LEN,
      DTD2.CHARACTER_OCTET_LENGTH AS XML_CHAR_OCT_LEN,
      DTD2.CHARACTER_SET_CATALOG AS XML_CHAR_SET_CAT,
      DTD2.CHARACTER_SET_SCHEMA AS XML_CHAR_SET_SCH,
      DTD2.CHARACTER_SET_NAME AS XML_CHAR_SET_NAME,
      DTD2.COLLATION_CATALOG AS XML_CHAR_COLL_CAT,
      DTD2.COLLATION_SCHEMA AS XML_CHAR_COLL_SCH,
      DTD2.COLLATION_NAME AS XML_CHAR_COLL_NAME,
      DTD2.DTD_IDENTIFIER AS XML_CHAR_DTD_ID,
      P.XML_OPTION, P.XML_PASSING_MECHANISM

*/
    
  
/* Modify the PARAMETERS view by inserting after the text:
     
            = ( DTD.OBJECT_CATALOG, DTD.OBJECT_SCHEMA, DTD.OBJECT_NAME,
                DTD.OBJECT_TYPE, DTD.DTD_IDENTIFIER )
   the text:
     
       LEFT JOIN
         DEFINITION_SCHEMA.DATA_TYPE_DESCRIPTOR DTD2
         ON ( P.SPECIFIC_CATALOG, P.SPECIFIC_SCHEMA, P.SPECIFIC_NAME,
              'ROUTINE', P.XML_STRING_DTD_IDENTIFIER )
          = ( DTD2.OBJECT_CATALOG, DTD2.OBJECT_SCHEMA, DTD2.OBJECT_NAME,
              DTD2.OBJECT_TYPE, DTD2.DTD_IDENTIFIER )

*/
    
  
/* Modify the ROUTINES view by inserting after the text:
     
           D.SCOPE_CATALOG, D.SCOPE_SCHEMA, D.SCOPE_NAME,
           D.MAXIMUM_CARDINALITY, D.DTD_IDENTIFIER,

   the text:
     
           D.XML_PRIMARY_MODIFIER, D.XML_SECONDARY_MODIFIER,
           D.XML_SCHEMA_CATALOG, D.XML_SCHEMA_SCHEMA, D.XML_SCHEMA_NAME,
           D.XML_SCHEMA_NAMESPACE, D.XML_SCHEMA_ELEMENT,

*/
    
  
/* Modify the ROUTINES view by inserting after the text:
     
           DT.MAXIMUM_CARDINALITY AS RESULT_CAST_MAX_CARDINALITY,
           DT.DTD_IDENTIFIER AS RESULT_CAST_DTD_IDENTIFIER,

   the text:
     
           DT.XML_PRIMARY_MODIFIER AS RESULT_CAST_XML_PRIMARY_MODIFIER,
           DT.XML_SECONDARY_MODIFIER AS RESULT_CAST_XML_SECONDARY_MODIFIER,
           DT.XML_SCHEMA_CATALOG AS RESULT_CAST_XML_SCHEMA_CATALOG,
           DT.XML_SCHEMA_SCHEMA AS RESULT_CAST_XML_SCHEMA_SCHEMA,
           DT.XML_SCHEMA_NAME AS RESULT_CAST_XML_SCHEMA_NAME,
           DT.XML_SCHEMA_NAMESPACE AS RESULT_CAST_XML_SCHEMA_NAMESPACE,
           DT.XML_SCHEMA_ELEMENT AS RESULT_CAST_XML_SCHEMA_ELEMENT,
           D2.DATA_TYPE AS XML_CHAR_TYPE,
           D2.CHARACTER_MAXIMUM_LENGTH AS XML_CHAR_MAX_LEN,
           D2.CHARACTER_OCTET_LENGTH AS XML_CHAR_OCT_LEN,
           D2.CHARACTER_SET_CATALOG AS XML_CHAR_SET_CAT,
           D2.CHARACTER_SET_SCHEMA AS XML_CHAR_SET_SCH,
           D2.CHARACTER_SET_NAME AS XML_CHAR_SET_NAME,
           D2.COLLATION_CATALOG AS XML_CHAR_COLL_CAT,
           D2.COLLATION_SCHEMA AS XML_CHAR_COLL_SCH,
           D2.COLLATION_NAME AS XML_CHAR_COLL_NAME,
           D2.DTD_IDENTIFIER AS XML_CHAR_DTD_ID,
           R.XML_OPTION, R.XML_RETURN_MECHANISM,

*/
    
  
/* Modify the ROUTINES view by inserting before the text:
     
     ( ( DEFINITION_SCHEMA.ROUTINES AS R

   the text:
     
    ( 

*/
    
  
/* Modify the ROUTINES view by inserting before the text:
     
    WHERE ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME ) IS NULL

   the text:
     
      LEFT JOIN
           DEFINITION_SCHEMA.DATA_TYPE_DESCRIPTOR AS D2
        ON ( SPECIFIC_CATALOG, SPECIFIC_SCHEMA, SPECIFIC_NAME,
             'ROUTINE', R.XML_STRING_DTD_IDENTIFIER )
         = ( D2.OBJECT_CATALOG, D2.OBJECT_SCHEMA, D2.OBJECT_NAME,
             D2.OBJECT_TYPE, D2.DTD_IDENTIFIER ) )

*/
    
  
CREATE VIEW XML_SCHEMA_ELEMENTS AS
  SELECT XS.XML_SCHEMA_TARGET_NAMESPACE, XS.XML_SCHEMA_LOCATION,
         XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA, XML_SCHEMA_NAME,
         XE.XML_SCHEMA_NAMESPACE, XE.XML_SCHEMA_ELEMENT,
         XE.XML_SCHEMA_ELEMENT_IS_DETERMINISTIC
  FROM DEFINITION_SCHEMA.XML_SCHEMA_ELEMENTS AS XE
  JOIN DEFINITION_SCHEMA.XML_SCHEMAS AS XS
  USING ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA, XML_SCHEMA_NAME )
  WHERE ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA,
          XML_SCHEMA_NAME, 'XML SCHEMA' )
       IN ( SELECT UP.OBJECT_CATALOG, UP.OBJECT_SCHEMA,
                   UP.OBJECT_NAME, UP.OBJECT_TYPE
            FROM DEFINITION_SCHEMA.USAGE_PRIVILEGES AS UP
            WHERE ( UP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                 OR
                    UP.GRANTEE IN ( SELECT ROLE_NAME
                                    FROM ENABLED_ROLES ) ) )
    AND XML_SCHEMA_CATALOG =
        ( SELECT CATALOG_NAME
          FROM INFORMATION_SCHEMA_CATALOG_NAME );

GRANT SELECT ON TABLE XML_SCHEMA_ELEMENTS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW XML_SCHEMA_NAMESPACES AS
    SELECT XS.XML_SCHEMA_TARGET_NAMESPACE, XS.XML_SCHEMA_LOCATION,
           XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA, XML_SCHEMA_NAME,
           XSN.XML_SCHEMA_NAMESPACE,
           XSN.XML_SCHEMA_NAMESPACE_IS_DETERMINISTIC
    FROM DEFINITION_SCHEMA.XML_SCHEMA_NAMESPACES AS XSN
    JOIN DEFINITION_SCHEMA.XML_SCHEMAS AS XS
    USING ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA, XML_SCHEMA_NAME )
    WHERE ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA,
            XML_SCHEMA_NAME, 'XML SCHEMA' )
        IN ( SELECT UP.OBJECT_CATALOG, UP.OBJECT_SCHEMA,
                    UP.OBJECT_NAME, UP.OBJECT_TYPE
             FROM DEFINITION_SCHEMA.USAGE_PRIVILEGES AS UP
             WHERE ( UP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                  OR
                     UP.GRANTEE IN ( SELECT ROLE_NAME
                                     FROM ENABLED_ROLES ) ) )
      AND XML_SCHEMA_CATALOG =
          ( SELECT CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME );

GRANT SELECT ON TABLE XML_SCHEMA_NAMESPACES
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW XML_SCHEMAS AS
    SELECT XML_SCHEMA_TARGET_NAMESPACE, XML_SCHEMA_LOCATION,
    XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA, XML_SCHEMA_NAME,
    XML_SCHEMA_IS_DETERMINISTIC, XML_SCHEMA_IS_PERMANENT
FROM DEFINITION_SCHEMA.XML_SCHEMAS
WHERE ( XML_SCHEMA_CATALOG, XML_SCHEMA_SCHEMA,
        XML_SCHEMA_NAME, 'XML SCHEMA' )
     IN ( SELECT UP.OBJECT_CATALOG, UP.OBJECT_SCHEMA,
                 UP.OBJECT_NAME, UP.OBJECT_TYPE
          FROM DEFINITION_SCHEMA.USAGE_PRIVILEGES AS UP
          WHERE ( UP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
       OR
          UP.GRANTEE IN ( SELECT ROLE_NAME
                          FROM ENABLED_ROLES ) ) )
   AND XML_SCHEMA_CATALOG =
       ( SELECT CATALOG_NAME
         FROM INFORMATION_SCHEMA_CATALOG_NAME );

GRANT SELECT ON TABLE XML_SCHEMAS
    TO PUBLIC WITH GRANT OPTION;

  