
/*
The following material is a "digital artifact" containing a series of complete
or partial SQL "schema definition" and/or "schema manipulation" statements
that effectively create or modify an SQL schema to support the facilities defined in one
part of ISO/IEC 9075. 

These statements may be used by SQL-implementations to create their initial
Information and Definition schemata. 
*/

      
      
/* Definition Schema */
      
INSERT INTO OBJECT_TYPES_LIST ( OBJECT_TYPE )
    VALUES ('PROPERTY GRAPH');

  
ALTER TABLE TABLES ADD
  CONSTRAINT TABLES_CHECK_NOT_PROPERTY_GRAPH
    CHECK ( NOT EXISTS (
              SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                     PROPERTY_GRAPH_NAME
               FROM PROPERTY_GRAPHS
               WHERE ( TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME )
                   = ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                       PROPERTY_GRAPH_NAME ) ) );

  
CREATE TABLE PG_DEFINED_LABEL_SETS (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    DEFINED_LABEL_SET_IDENTIFIER                 INFORMATION_SCHEMA.SQL_IDENTIFIER,
    
    CONSTRAINT PG_DEFINED_LABEL_SETS_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, DEFINED_LABEL_SET_IDENTIFIER ),
                    
    CONSTRAINT PG_DEFINED_LABEL_SETS_FOREIGN_KEY_PROPERTY_GRAPHS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                    PROPERTY_GRAPH_NAME )
        REFERENCES PROPERTY_GRAPHS
    );

  
CREATE TABLE PG_DEFINED_LABEL_SET_LABELS (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    DEFINED_LABEL_SET_IDENTIFIER                 INFORMATION_SCHEMA.SQL_IDENTIFIER,
    LABEL_NAME                                   INFORMATION_SCHEMA.SQL_IDENTIFIER,
    
    CONSTRAINT PG_DEFINED_LABEL_SET_LABELS_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                    PROPERTY_GRAPH_NAME, DEFINED_LABEL_SET_IDENTIFIER, LABEL_NAME ),
                    
    CONSTRAINT PG_DEFINED_LABEL_SET_LABELS_FOREIGN_KEY_PG_DEFINED_LABEL_SETS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                    PROPERTY_GRAPH_NAME, DEFINED_LABEL_SET_IDENTIFIER )
        REFERENCES PG_DEFINED_LABEL_SETS,
        
    CONSTRAINT PG_DEFINED_LABEL_SET_LABELS_FOREIGN_KEY_PG_LABELS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                    PROPERTY_GRAPH_NAME, LABEL_NAME )
        REFERENCES PG_LABELS
    );

  
CREATE TABLE PG_EDGE_DEFINED_LABEL_SETS (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    EDGE_DEFINED_LABEL_SET_IDENTIFIER            INFORMATION_SCHEMA.SQL_IDENTIFIER,
    IS_DIRECTED                                  INFORMATION_SCHEMA.YES_OR_NO
      CONSTRAINT PG_EDGE_DEFINED_LABEL_SETS_IS_DIRECTED_NOT_NULL
        NOT NULL,
    IS_UNDIRECTED                                INFORMATION_SCHEMA.YES_OR_NO
      CONSTRAINT PG_EDGE_DEFINED_LABEL_SETS_IS_UNDIRECTED_NOT_NULL
        NOT NULL,
        
    CONSTRAINT PG_EDGE_DEFINED_LABEL_SETS_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                    PROPERTY_GRAPH_NAME, EDGE_DEFINED_LABEL_SET_IDENTIFIER ),
                    
    CONSTRAINT PG_EDGE_DEFINED_LABEL_SETS_FOREIGN_KEY_PG_DEFINED_LABEL_SETS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                    PROPERTY_GRAPH_NAME, EDGE_DEFINED_LABEL_SET_IDENTIFIER )
        REFERENCES PG_DEFINED_LABEL_SETS,
        
    CONSTRAINT PG_EDGE_DEFINED_LABEL_SETS_CHECK_DIRECTED_UNDIRECTED
      CHECK ( NOT ( IS_DIRECTED = 'NO' 
                 AND 
                    IS_UNDIRECTED = 'NO' ) )
    );

  
CREATE TABLE PG_EDGE_TABLE_COMPONENTS (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    EDGE_TABLE_ALIAS                             INFORMATION_SCHEMA.SQL_IDENTIFIER,
    VERTEX_TABLE_ALIAS                           INFORMATION_SCHEMA.SQL_IDENTIFIER,
    EDGE_END                                     INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT PG_EDGE_TABLE_COMPONENTS_CHECK_EDGE_END
        CHECK ( EDGE_END IN ( 'DESTINATION', 'SOURCE' ) ),
    EDGE_TABLE_COLUMN_NAME                       INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT PG_EDGE_TABLE_COMPONENTS_EDGE_TABLE_COLUMN_NAME_NOT_NULL
        NOT NULL,
    VERTEX_TABLE_COLUMN_NAME                     INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT PG_EDGE_TABLE_COMPONENTS_VERTEX_TABLE_COLUMN_NAME_NOT_NULL
        NOT NULL,
    ORDINAL_POSITION                             INFORMATION_SCHEMA.CARDINAL_NUMBER
      CONSTRAINT PG_EDGE_TABLE_COMPONENTS_CHECK_ORDINAL_POSITION_GREATER_THAN_ZERO
        CHECK ( ORDINAL_POSITION > 0 )
      CONSTRAINT PG_EDGE_TABLE_COMPONENTS_CHECK_ORDINAL_POSITION_CONTIGUOUS
        CHECK ( 0 = ALL ( SELECT MAX(ORDINAL_POSITION) - COUNT(*)
                          FROM PG_EDGE_TABLE_COMPONENTS
                          GROUP BY PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                                   PROPERTY_GRAPH_NAME, EDGE_TABLE_ALIAS ) ),

    CONSTRAINT PG_EDGE_TABLE_COMPONENTS_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, EDGE_TABLE_ALIAS, VERTEX_TABLE_ALIAS,
                    EDGE_END, ORDINAL_POSITION),

    CONSTRAINT PG_EDGE_TABLE_COMPONENTS_FOREIGN_KEY_EDGE_IN_PG_ELEMENT_TABLES
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, EDGE_TABLE_ALIAS )
        REFERENCES PG_ELEMENT_TABLES,

    CONSTRAINT PG_EDGE_TABLE_COMPONENTS_FOREIGN_KEY_VERTEX_IN_PG_ELEMENT_TABLES
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, VERTEX_TABLE_ALIAS )
        REFERENCES PG_ELEMENT_TABLES,

    CONSTRAINT PG_EDGE_TABLE_COMPONENTS_UNIQUE_EDGE_COLUMN
      UNIQUE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
               EDGE_TABLE_ALIAS, VERTEX_TABLE_ALIAS, EDGE_TABLE_COLUMN_NAME ),

    CONSTRAINT PG_EDGE_TABLE_COMPONENTS_UNIQUE_VERTEX_COLUMN
      UNIQUE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
               EDGE_TABLE_ALIAS, VERTEX_TABLE_ALIAS, VERTEX_TABLE_COLUMN_NAME )
    );

  
CREATE TABLE PG_EDGE_TRIPLETS (
    PROPERTY_GRAPH_CATALOG                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                           INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                             INFORMATION_SCHEMA.SQL_IDENTIFIER,
    EDGE_TRIPLET_DEFINED_LABEL_SET_IDENTIFIER       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    SOURCE_VERTEX_DEFINED_LABEL_SET_IDENTIFIER      INFORMATION_SCHEMA.SQL_IDENTIFIER,
    DESTINATION_VERTEX_DEFINED_LABEL_SET_IDENTIFIER INFORMATION_SCHEMA.SQL_IDENTIFIER,
    IS_DIRECTED                                     INFORMATION_SCHEMA.YES_OR_NO,

    CONSTRAINT PG_EDGE_TRIPLETS_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
                    EDGE_TRIPLET_DEFINED_LABEL_SET_IDENTIFIER,
                    SOURCE_VERTEX_DEFINED_LABEL_SET_IDENTIFIER,
                    DESTINATION_VERTEX_DEFINED_LABEL_SET_IDENTIFIER, IS_DIRECTED ),

    CONSTRAINT PG_EDGE_TRIPLETS_CHECK_PG_EDGE_DEFINED_LABEL_SETS
      CHECK ( ( IS_DIRECTED = 'YES'
           AND
               ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
                 EDGE_TRIPLET_DEFINED_LABEL_SET_IDENTIFIER ) IN
                 ( SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                          PROPERTY_GRAPH_NAME, EDGE_DEFINED_LABEL_SET_IDENTIFIER
                   FROM PG_EDGE_DEFINED_LABEL_SETS
                   WHERE IS_DIRECTED = 'YES' ) )
             OR
              ( IS_DIRECTED = 'NO'
             AND
                ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                  PROPERTY_GRAPH_NAME, EDGE_TRIPLET_DEFINED_LABEL_SET_IDENTIFIER ) IN
                  ( SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                           PROPERTY_GRAPH_NAME, EDGE_DEFINED_LABEL_SET_IDENTIFIER
                    FROM PG_EDGE_DEFINED_LABEL_SETS
                    WHERE IS_UNDIRECTED = 'YES' ) ) ),

    CONSTRAINT PG_EDGE_TRIPLETS_FOREIGN_KEY_SOURCE_VERTEX_DEFINED_LABEL_SETS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                    PROPERTY_GRAPH_NAME, SOURCE_VERTEX_DEFINED_LABEL_SET_IDENTIFIER )
        REFERENCES PG_VERTEX_DEFINED_LABEL_SETS,

    CONSTRAINT PG_EDGE_TRIPLETS_FOREIGN_KEY_DESTINATION_VERTEX_DEFINED_LABEL_SETS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, 
                    DESTINATION_VERTEX_DEFINED_LABEL_SET_IDENTIFIER )
        REFERENCES PG_VERTEX_DEFINED_LABEL_SETS
    );

  
CREATE TABLE PG_ELEMENT_TABLE_KEY_COLUMNS (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    ELEMENT_TABLE_ALIAS                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    COLUMN_NAME                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    ORDINAL_POSITION                             INFORMATION_SCHEMA.CARDINAL_NUMBER
      CONSTRAINT PG_ELEMENT_TABLE_KEY_COLUMNS_ORDINAL_POSITION_NOT_NULL
        NOT NULL
      CONSTRAINT 
        PG_ELEMENT_TABLE_KEY_COLUMNS_CHECK_ORDINAL_POSITION_GREATER_THAN_ZERO
        CHECK ( ORDINAL_POSITION > 0 )
      CONSTRAINT PG_ELEMENT_TABLE_KEY_COLUMNS_CHECK_ORDINAL_POSITION_CONTIGUOUS
        CHECK ( 0 = ALL ( SELECT MAX(ORDINAL_POSITION) - COUNT(*)
                          FROM PG_ELEMENT_TABLE_KEY_COLUMNS
                          GROUP BY PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                                   PROPERTY_GRAPH_NAME, ELEMENT_TABLE_ALIAS ) ),

    CONSTRAINT PG_ELEMENT_TABLE_KEY_COLUMNS_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                    PROPERTY_GRAPH_NAME, ELEMENT_TABLE_ALIAS, COLUMN_NAME ),

    CONSTRAINT PG_ELEMENT_TABLE_KEY_COLUMNS_FOREIGN_KEY_PG_ELEMENT_TABLES
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, ELEMENT_TABLE_ALIAS )
        REFERENCES PG_ELEMENT_TABLES,

    CONSTRAINT PG_ELEMENT_TABLE_KEY_COLUMNS_UNIQUE
      UNIQUE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
               ELEMENT_TABLE_ALIAS, ORDINAL_POSITION )
    );

  
CREATE TABLE PG_ELEMENT_TABLE_LABELS (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    ELEMENT_TABLE_ALIAS                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    LABEL_NAME                                   INFORMATION_SCHEMA.SQL_IDENTIFIER,

    CONSTRAINT PG_ELEMENT_TABLE_LABELS_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, ELEMENT_TABLE_ALIAS, LABEL_NAME ),

    CONSTRAINT PG_ELEMENT_TABLE_LABELS_FOREIGN_KEY_PG_ELEMENT_TABLES
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, ELEMENT_TABLE_ALIAS )
        REFERENCES PG_ELEMENT_TABLES,

    CONSTRAINT PG_ELEMENT_TABLE_LABELS_CHECK_LABEL_NAME
      CHECK ( ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
                LABEL_NAME ) IN
                ( SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                         PROPERTY_GRAPH_NAME, LABEL_NAME
                  FROM PG_LABEL_PROPERTIES ) )
    );

  
CREATE TABLE PG_ELEMENT_TABLE_PROPERTIES (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    ELEMENT_TABLE_ALIAS                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_NAME                                INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_EXPRESSION                          INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT PG_ELEMENT_TABLE_PROPERTIES_PROPERTY_EXPRESSION_NOT_NULL
        NOT NULL,

    CONSTRAINT PG_ELEMENT_TABLE_PROPERTIES_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, ELEMENT_TABLE_ALIAS, PROPERTY_NAME ),

    CONSTRAINT PG_ELEMENT_TABLE_PROPERTIES_FOREIGN_KEY_PG_ELEMENT_TABLES
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, ELEMENT_TABLE_ALIAS )
        REFERENCES PG_ELEMENT_TABLES,

    CONSTRAINT PPG_ELEMENT_TABLE_PROPERTIES_CHECK_PROPERTY_NAME
      CHECK ( ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
                PROPERTY_NAME ) IN
               ( SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                        PROPERTY_GRAPH_NAME, PROPERTY_NAME
                 FROM PG_LABEL_PROPERTIES ) )
    );

  
CREATE TABLE PG_ELEMENT_TABLES (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    ELEMENT_TABLE_ALIAS                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    ELEMENT_TABLE_KIND                           INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT PG_ELEMENT_TABLES_ELEMENT_TABLE_KIND_NOT_NULL
        NOT NULL
      CONSTRAINT PG_ELEMENT_TABLES_CHECK_ELEMENT_TABLE_KIND
        CHECK ( ELEMENT_TABLE_KIND IN ( 'EDGE', 'VERTEX' ) ),
    TABLE_CATALOG                                INFORMATION_SCHEMA.SQL_IDENTIFIER,
    TABLE_SCHEMA                                 INFORMATION_SCHEMA.SQL_IDENTIFIER,
    TABLE_NAME                                   INFORMATION_SCHEMA.SQL_IDENTIFIER,
    ELEMENT_TABLE_DEFINITION                     INFORMATION_SCHEMA.CHARACTER_DATA,

    CONSTRAINT PG_ELEMENT_TABLES_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, ELEMENT_TABLE_ALIAS ),

    CONSTRAINT PG_ELEMENT_TABLES_FOREIGN_KEY_PROPERTY_GRAPHS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME )
        REFERENCES PROPERTY_GRAPHS,

    CONSTRAINT PG_ELEMENT_TABLES_CHECK_ELEMENT_TABLE_DEFINITION
      CHECK ( ( ELEMENT_TABLE_DEFINITION IS NOT NULL
           AND
              ( TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME ) IS NULL )
             OR
              ( ELEMENT_TABLE_DEFINITION IS NULL
           AND
              ( TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME ) IN
                ( SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
                  FROM TABLES ) ) )
    );

  
CREATE TABLE PG_LABEL_PROPERTIES (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    LABEL_NAME                                   INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_NAME                                INFORMATION_SCHEMA.SQL_IDENTIFIER,

    CONSTRAINT PG_LABEL_PROPERTIES_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, LABEL_NAME, PROPERTY_NAME ),

    CONSTRAINT PG_LABEL_PROPERTIES_FOREIGN_KEY_PROPERTY_GRAPHS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME )
        REFERENCES PROPERTY_GRAPHS,

    CONSTRAINT PG_LABEL_PROPERTIES_FOREIGN_KEY_PG_LABELS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, LABEL_NAME )
        REFERENCES PG_LABELS,

    CONSTRAINT PG_LABEL_PROPERTIES_CHECK_PROPERTY_NAME
      CHECK ( ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
                PROPERTY_NAME ) IN
                ( SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                         PROPERTY_GRAPH_NAME, PROPERTY_NAME
                  FROM PG_ELEMENT_TABLE_PROPERTIES ) ),

    CONSTRAINT PG_LABEL_PROPERTIES_CHECK_LABEL_NAME
      CHECK ( ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
                LABEL_NAME ) IN
               ( SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                        PROPERTY_GRAPH_NAME, LABEL_NAME
                 FROM PG_ELEMENT_TABLE_LABELS ) )
    );

  
CREATE TABLE PG_LABELS (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    LABEL_NAME                                   INFORMATION_SCHEMA.SQL_IDENTIFIER,

    CONSTRAINT PG_LABELS_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, LABEL_NAME ),

    CONSTRAINT PG_LABELS_FOREIGN_KEY_PROPERTY_GRAPHS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME )
        REFERENCES PROPERTY_GRAPHS,

    CONSTRAINT PG_LABELS_CHECK_LABEL_NAME
      CHECK ( ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
                LABEL_NAME ) IN
               ( SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                        PROPERTY_GRAPH_NAME, LABEL_NAME
                 FROM PG_ELEMENT_TABLE_LABELS ) )
   );

  
CREATE TABLE PG_PROPERTY_DATA_TYPES (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_NAME                                INFORMATION_SCHEMA.SQL_IDENTIFIER,
    DTD_IDENTIFIER                               INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT PG_PROPERTY_DATA_TYPES_DTD_IDENTIFIER_NOT_NULL
        NOT NULL,

    CONSTRAINT PG_PROPERTY_DATA_TYPES_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, PROPERTY_NAME ),

    CONSTRAINT PG_PROPERTY_DATA_TYPES_FOREIGN_KEY_PROPERTY_GRAPHS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME )
        REFERENCES PROPERTY_GRAPHS,

    CONSTRAINT PG_PROPERTY_DATA_TYPES_CHECK_DATA_TYPE
      CHECK ( ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME, 
                'PROPERTY GRAPH', DTD_IDENTIFIER ) IN
               ( SELECT OBJECT_CATALOG, OBJECT_SCHEMA, OBJECT_NAME, OBJECT_TYPE, 
                        DTD_IDENTIFIER
                 FROM DATA_TYPE_DESCRIPTOR ) ),

    CONSTRAINT PPG_PROPERTY_DATA_TYPES_CHECK_PROPERTY_NAME
      CHECK ( ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME, 
                PROPERTY_NAME ) IN 
                ( SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                         PROPERTY_GRAPH_NAME, PROPERTY_NAME
                  FROM PG_ELEMENT_TABLE_PROPERTIES ) )
    );

  
CREATE TABLE PG_PROPERTY_GRAPH_PRIVILEGES (
    GRANTOR                                      INFORMATION_SCHEMA.SQL_IDENTIFIER,
    GRANTEE                                      INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PRIVILEGE_TYPE                               INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT PG_PROPERTY_GRAPH_PRIVILEGES_CHECK_PRIVILEGE_TYPE
        CHECK ( PRIVILEGE_TYPE IN ( 'SELECT' ) ),
    IS_GRANTABLE                                 INFORMATION_SCHEMA.YES_OR_NO
      CONSTRAINT PG_PROPERTY_GRAPH_PRIVILEGES_IS_GRANTABLE_NOT_NULL
        NOT NULL,

    CONSTRAINT PG_PROPERTY_GRAPH_PRIVILEGES_PRIMARY_KEY
      PRIMARY KEY ( GRANTOR, GRANTEE, PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                    PROPERTY_GRAPH_NAME, PRIVILEGE_TYPE ),

    CONSTRAINT PG_PROPERTY_GRAPH_PRIVILEGES_FOREIGN_KEY_PROPERTY_GRAPHS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME )
        REFERENCES PROPERTY_GRAPHS,

    CONSTRAINT PG_PROPERTY_GRAPH_PRIVILEGES_GRANTOR_CHECK
      CHECK ( GRANTOR = '_SYSTEM'
             OR
              GRANTOR IN ( SELECT AUTHORIZATION_NAME
                           FROM AUTHORIZATIONS ) ),

    CONSTRAINT PG_PROPERTY_GRAPH_PRIVILEGES_GRANTEE_CHECK
      CHECK ( GRANTEE = 'PUBLIC'
             OR
              GRANTEE IN ( SELECT AUTHORIZATION_NAME
                           FROM AUTHORIZATIONS ) )
    );

  
CREATE TABLE PG_VERTEX_DEFINED_LABEL_SETS (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    VERTEX_DEFINED_LABEL_SET_IDENTIFIER          INFORMATION_SCHEMA.SQL_IDENTIFIER,

    CONSTRAINT PG_VERTEX_DEFINED_LABEL_SETS_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, VERTEX_DEFINED_LABEL_SET_IDENTIFIER ),

    CONSTRAINT PG_VERTEX_DEFINED_LABEL_SETS_FOREIGN_KEY_PG_DEFINED_LABEL_SETS
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME, VERTEX_DEFINED_LABEL_SET_IDENTIFIER )
        REFERENCES PG_DEFINED_LABEL_SETS
    );

  
CREATE TABLE PROPERTY_GRAPHS (
    PROPERTY_GRAPH_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_SCHEMA                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PROPERTY_GRAPH_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,

    CONSTRAINT PROPERTY_GRAPHS_PRIMARY_KEY
      PRIMARY KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
                    PROPERTY_GRAPH_NAME ),

    CONSTRAINT PROPERTY_GRAPHS_FOREIGN_KEY_SCHEMATA
      FOREIGN KEY ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA )
        REFERENCES SCHEMATA,

    CONSTRAINT PROPERTY_GRAPHS_CHECK_NOT_TABLE
      CHECK ( NOT EXISTS ( SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
                           FROM TABLES
                           WHERE ( TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME ) 
                               = ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, 
                                   PROPERTY_GRAPH_NAME ) )
    );

  
      
      
/* Information Schema */      
      
CREATE VIEW PG_DEFINED_LABEL_SETS AS
    SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
           DEFINED_LABEL_SET_IDENTIFIER
    FROM DEFINITION_SCHEMA.PG_DEFINED_LABEL_SETS
    WHERE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME ) IN
            ( SELECT PGP.PROPERTY_GRAPH_CATALOG, PGP.PROPERTY_GRAPH_SCHEMA, 
                     PGP.PROPERTY_GRAPH_NAME
              FROM DEFINITION_SCHEMA.PG_PROPERTY_GRAPH_PRIVILEGES AS PGP
              WHERE ( PGP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                     OR
                      PGP.GRANTEE IN ( SELECT ROLE_NAME FROM ENABLED_ROLES ) ) )
       AND
          PROPERTY_GRAPH_CATALOG = ( SELECT CATALOG_NAME
                                     FROM INFORMATION_SCHEMA_CATALOG_NAME );
                                       
GRANT SELECT ON TABLE PG_DEFINED_LABEL_SETS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_DEFINED_LABEL_SET_LABELS AS
    SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME, 
           DEFINED_LABEL_SET_IDENTIFIER, LABEL_NAME
    FROM DEFINITION_SCHEMA.PG_DEFINED_LABEL_SET_LABELS
    WHERE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME ) IN
            ( SELECT PGP.PROPERTY_GRAPH_CATALOG, PGP.PROPERTY_GRAPH_SCHEMA, 
                     PGP.PROPERTY_GRAPH_NAME
              FROM DEFINITION_SCHEMA.PG_PROPERTY_GRAPH_PRIVILEGES AS PGP
              WHERE ( PGP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                     OR
                      PGP.GRANTEE IN ( SELECT ROLE_NAME
                                       FROM ENABLED_ROLES ) ) )
       AND
          PROPERTY_GRAPH_CATALOG = ( SELECT CATALOG_NAME
                                     FROM INFORMATION_SCHEMA_CATALOG_NAME );

GRANT SELECT ON TABLE PG_DEFINED_LABEL_SET_LABELS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_EDGE_DEFINED_LABEL_SETS AS
    SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME, 
           EDGE_DEFINED_LABEL_SET_IDENTIFIER, IS_DIRECTED, IS_UNDIRECTED
    FROM DEFINITION_SCHEMA.PG_EDGE_DEFINED_LABEL_SETS
    WHERE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME ) IN
            ( SELECT PGP.PROPERTY_GRAPH_CATALOG, PGP.PROPERTY_GRAPH_SCHEMA, 
                     PGP.PROPERTY_GRAPH_NAME
              FROM DEFINITION_SCHEMA.PG_PROPERTY_GRAPH_PRIVILEGES AS PGP
              WHERE ( PGP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                     OR
                      PGP.GRANTEE IN ( SELECT ROLE_NAME
                                       FROM ENABLED_ROLES ) ) )
       AND
          PROPERTY_GRAPH_CATALOG = ( SELECT CATALOG_NAME
                                     FROM INFORMATION_SCHEMA_CATALOG_NAME );

GRANT SELECT ON TABLE PG_EDGE_DEFINED_LABEL_SETS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_EDGE_TABLE_COMPONENTS AS
    SELECT ETC.PROPERTY_GRAPH_CATALOG, ETC.PROPERTY_GRAPH_SCHEMA, 
           ETC.PROPERTY_GRAPH_NAME, ETC.EDGE_TABLE_ALIAS, ETC.VERTEX_TABLE_ALIAS, 
           ETC.EDGE_END, ETC.EDGE_TABLE_COLUMN_NAME, ETC.VERTEX_TABLE_COLUMN_NAME,
           ETC.ORDINAL_POSITION
    FROM DEFINITION_SCHEMA.PG_EDGE_TABLE_COMPONENTS AS ETC
      JOIN 
         DEFINITION_SCHEMA.SCHEMATA AS S
        ON ( ( ETC.PROPERTY_GRAPH_CATALOG, ETC.PROPERTY_GRAPH_SCHEMA )
           = ( S.CATALOG_NAME, S.SCHEMA_NAME ) )
    WHERE ( S.SCHEMA_OWNER = CURRENT_USER
           OR
            S.SCHEMA_OWNER IN ( SELECT ER.ROLE_NAME
                                FROM ENABLED_ROLES AS ER ) )
       AND
          ETC.PROPERTY_GRAPH_CATALOG 
        = ( SELECT ISCN.CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME AS ISCN );
                                         
GRANT SELECT ON TABLE PG_EDGE_TABLE_COMPONENTS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_EDGE_TRIPLETS AS
    SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
           EDGE_TRIPLET_DEFINED_LABEL_SET_IDENTIFIER,
           SOURCE_VERTEX_DEFINED_LABEL_SET_IDENTIFIER,
           DESTINATION_VERTEX_DEFINED_LABEL_SET_IDENTIFIER, IS_DIRECTED
    FROM DEFINITION_SCHEMA.PG_EDGE_TRIPLETS
    WHERE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME ) IN
            ( SELECT PGP.PROPERTY_GRAPH_CATALOG, PGP.PROPERTY_GRAPH_SCHEMA, 
                     PGP.PROPERTY_GRAPH_NAME
              FROM DEFINITION_SCHEMA.PG_PROPERTY_GRAPH_PRIVILEGES AS PGP
              WHERE ( PGP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                     OR
                      PGP.GRANTEE IN ( SELECT ROLE_NAME
                                       FROM ENABLED_ROLES ) ) )
       AND
          PROPERTY_GRAPH_CATALOG = ( SELECT CATALOG_NAME
                                     FROM INFORMATION_SCHEMA_CATALOG_NAME );

GRANT SELECT ON TABLE PG_EDGE_TRIPLETS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_ELEMENT_TABLE_KEY_COLUMNS AS
    SELECT ETKC.PROPERTY_GRAPH_CATALOG, ETKC.PROPERTY_GRAPH_SCHEMA,
           ETKC.PROPERTY_GRAPH_NAME, ETKC.ELEMENT_TABLE_ALIAS, ETKC.COLUMN_NAME, 
           ETKC.ORDINAL_POSITION
    FROM DEFINITION_SCHEMA.PG_ELEMENT_TABLE_KEY_COLUMNS AS ETKC
      JOIN 
         DEFINITION_SCHEMA.SCHEMATA AS S
        ON ( ( ETKC.PROPERTY_GRAPH_CATALOG, ETKC.PROPERTY_GRAPH_SCHEMA )
           = ( S.CATALOG_NAME, S.SCHEMA_NAME ) )
    WHERE ( S.SCHEMA_OWNER = CURRENT_USER
           OR
            S.SCHEMA_OWNER IN ( SELECT ER.ROLE_NAME
                                FROM ENABLED_ROLES AS ER ) )
       AND
          ETKC.PROPERTY_GRAPH_CATALOG 
        = ( SELECT ISCN.CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME AS ISCN );

GRANT SELECT ON TABLE PG_ELEMENT_TABLE_KEY_COLUMNS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_ELEMENT_TABLE_LABELS AS
    SELECT ETL.PROPERTY_GRAPH_CATALOG, ETL.PROPERTY_GRAPH_SCHEMA, 
           ETL.PROPERTY_GRAPH_NAME, ETL.ELEMENT_TABLE_ALIAS, ETL.LABEL_NAME
    FROM DEFINITION_SCHEMA.PG_ELEMENT_TABLE_LABELS AS ETL
      JOIN 
         DEFINITION_SCHEMA.SCHEMATA AS S
        ON ( ( ETL.PROPERTY_GRAPH_CATALOG, ETL.PROPERTY_GRAPH_SCHEMA )
           = ( S.CATALOG_NAME, S.SCHEMA_NAME ) )
    WHERE ( S.SCHEMA_OWNER = CURRENT_USER
           OR
            S.SCHEMA_OWNER IN ( SELECT ER.ROLE_NAME
                                FROM ENABLED_ROLES AS ER ) )
       AND
          ETL.PROPERTY_GRAPH_CATALOG 
        = ( SELECT ISCN.CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME AS ISCN );

GRANT SELECT ON TABLE PG_ELEMENT_TABLE_LABELS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_ELEMENT_TABLE_PROPERTIES AS
    SELECT ETP.PROPERTY_GRAPH_CATALOG, ETP.PROPERTY_GRAPH_SCHEMA, 
           ETP.PROPERTY_GRAPH_NAME, ETP.ELEMENT_TABLE_ALIAS, ETP.PROPERTY_NAME, 
           ETP.PROPERTY_EXPRESSION
    FROM DEFINITION_SCHEMA.PG_ELEMENT_TABLE_PROPERTIES AS ETP
      JOIN 
          DEFINITION_SCHEMA.SCHEMATA AS S
         ON ( ( ETP.PROPERTY_GRAPH_CATALOG, ETP.PROPERTY_GRAPH_SCHEMA )
            = ( S.CATALOG_NAME, S.SCHEMA_NAME ) )
    WHERE ( S.SCHEMA_OWNER = CURRENT_USER
           OR
            S.SCHEMA_OWNER IN ( SELECT ER.ROLE_NAME
                                FROM ENABLED_ROLES AS ER ) )
       AND
          ETP.PROPERTY_GRAPH_CATALOG 
        = ( SELECT ISCN.CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME AS ISCN );

GRANT SELECT ON TABLE PG_ELEMENT_PROPERTIES
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_ELEMENT_TABLES AS
    SELECT ET.PROPERTY_GRAPH_CATALOG, ET.PROPERTY_GRAPH_SCHEMA, 
           ET.PROPERTY_GRAPH_NAME, ET.ELEMENT_TABLE_ALIAS, ET.ELEMENT_TABLE_KIND, 
           ET.TABLE_CATALOG, ET.TABLE_SCHEMA, ET.TABLE_NAME, 
           ET.ELEMENT_TABLE_DEFINITION
    FROM DEFINITION_SCHEMA.PG_ELEMENT_TABLES AS ET
      JOIN 
         DEFINITION_SCHEMA.SCHEMATA AS S
        ON ( ( ET.PROPERTY_GRAPH_CATALOG, ET.PROPERTY_GRAPH_SCHEMA )
           = ( S.CATALOG_NAME, S.SCHEMA_NAME ) )
    WHERE ( S.SCHEMA_OWNER = CURRENT_USER
           OR
            S.SCHEMA_OWNER IN ( SELECT ER.ROLE_NAME
                                FROM ENABLED_ROLES AS ER ) )
       AND
          ET.PROPERTY_GRAPH_CATALOG 
        = ( SELECT ISCN.CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME AS ISCN );

GRANT SELECT ON TABLE PG_ELEMENT_TABLES
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_LABEL_PROPERTIES AS
    SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
           LABEL_NAME, PROPERTY_NAME
    FROM DEFINITION_SCHEMA.PG_LABEL_PROPERTIES
    WHERE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME )
            IN ( SELECT PGP.PROPERTY_GRAPH_CATALOG, PGP.PROPERTY_GRAPH_SCHEMA, 
                        PGP.PROPERTY_GRAPH_NAME
                 FROM DEFINITION_SCHEMA.PG_PROPERTY_GRAPH_PRIVILEGES AS PGP
                 WHERE ( PGP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                        OR
                         PGP.GRANTEE IN ( SELECT ROLE_NAME
                                          FROM ENABLED_ROLES ) ) )
       AND
          PROPERTY_GRAPH_CATALOG = ( SELECT CATALOG_NAME
                                     FROM INFORMATION_SCHEMA_CATALOG_NAME );

GRANT SELECT ON TABLE PG_LABEL_PROPERTIES
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_LABELS AS
    SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME,
           LABEL_NAME
    FROM DEFINITION_SCHEMA.PG_LABELS
    WHERE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME )
            IN ( SELECT PGP.PROPERTY_GRAPH_CATALOG, PGP.PROPERTY_GRAPH_SCHEMA, 
                        PGP.PROPERTY_GRAPH_NAME
                 FROM DEFINITION_SCHEMA.PG_PROPERTY_GRAPH_PRIVILEGES AS PGP
                 WHERE ( PGP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                        OR
                         PGP.GRANTEE IN ( SELECT ROLE_NAME
                                          FROM ENABLED_ROLES ) ) )
       AND
          PROPERTY_GRAPH_CATALOG = ( SELECT CATALOG_NAME
                                     FROM INFORMATION_SCHEMA_CATALOG_NAME );
                                     
GRANT SELECT ON TABLE PG_LABELS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_PROPERTY_DATA_TYPES AS
    SELECT PGT.PROPERTY_GRAPH_CATALOG, PGT.PROPERTY_GRAPH_SCHEMA, 
           PGT.PROPERTY_GRAPH_NAME, PGT.PROPERTY_NAME, D.DATA_TYPE, 
           D.CHARACTER_MAXIMUM_LENGTH, D.CHARACTER_OCTET_LENGTH, 
           D.CHARACTER_SET_CATALOG, D.CHARACTER_SET_SCHEMA, D.CHARACTER_SET_NAME,
           D.COLLATION_CATALOG, D.COLLATION_SCHEMA, D.COLLATION_NAME,
           D.NUMERIC_PRECISION, D.NUMERIC_PRECISION_RADIX, D.NUMERIC_SCALE,
           D.DATETIME_PRECISION, D.INTERVAL_TYPE, D.INTERVAL_PRECISION,
           D.USER_DEFINED_TYPE_CATALOG, D.USER_DEFINED_TYPE_SCHEMA, 
           D.USER_DEFINED_TYPE_NAME, D.SCOPE_CATALOG, D.SCOPE_SCHEMA, D.SCOPE_NAME,
           D.MAXIMUM_CARDINALITY, D.DECLARED_DATA_TYPE, D.DECLARED_NUMERIC_PRECISION,
           D.DECLARED_NUMERIC_SCALE, D.DTD_IDENTIFIER
    FROM DEFINITION_SCHEMA.PG_PROPERTY_DATA_TYPES AS PGT
      JOIN 
         DEFINITION_SCHEMA.DATA_TYPE_DESCRIPTOR AS D
        ON ( ( PGT.PROPERTY_GRAPH_CATALOG, PGT.PROPERTY_GRAPH_SCHEMA, 
               PGT.PROPERTY_GRAPH_NAME, 'PROPERTY GRAPH', PGT.DTD_IDENTIFIER )
           = ( D.OBJECT_CATALOG, D.OBJECT_SCHEMA, D.OBJECT_NAME, D.OBJECT_TYPE,
               D.DTD_IDENTIFIER ) )
    WHERE ( PGT.PROPERTY_GRAPH_CATALOG, PGT.PROPERTY_GRAPH_SCHEMA,
            PGT.PROPERTY_GRAPH_NAME ) IN
            ( SELECT PGP.PROPERTY_GRAPH_CATALOG, PGP.PROPERTY_GRAPH_SCHEMA, 
                     PGP.PROPERTY_GRAPH_NAME
               FROM DEFINITION_SCHEMA.PG_PROPERTY_GRAPH_PRIVILEGES AS PGP
               WHERE ( PGP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                      OR
                       PGP.GRANTEE IN ( SELECT ROLE_NAME
                                        FROM ENABLED_ROLES ) ) )
       AND
          PGT.PROPERTY_GRAPH_CATALOG = ( SELECT CATALOG_NAME
                                         FROM INFORMATION_SCHEMA_CATALOG_NAME );
                                         
GRANT SELECT ON TABLE PG_PROPERTY_DATA_TYPES
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_PROPERTY_GRAPH_PRIVILEGES AS
    SELECT GRANTOR, GRANTEE, PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA,
           PROPERTY_GRAPH_NAME, PRIVILEGE_TYPE, IS_GRANTABLE
    FROM DEFINITION_SCHEMA.PG_PROPERTY_GRAPH_PRIVILEGES
    WHERE ( GRANTEE IN ( 'PUBLIC', CURRENT_USER )
           OR
            GRANTEE IN ( SELECT ROLE_NAME
                         FROM ENABLED_ROLES )
           OR
            GRANTOR = CURRENT_USER
           OR
            GRANTOR IN ( SELECT ROLE_NAME
                         FROM ENABLED_ROLES ) )
       AND
          PROPERTY_GRAPH_CATALOG = ( SELECT CATALOG_NAME
                                     FROM INFORMATION_SCHEMA_CATALOG_NAME );
                                     
GRANT SELECT ON TABLE PG_PROPERTY_GRAPH_PRIVILEGES
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PG_VERTEX_DEFINED_LABEL_SETS AS
    SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME, 
           VERTEX_DEFINED_LABEL_SET_IDENTIFIER
    FROM DEFINITION_SCHEMA.PG_VERTEX_DEFINED_LABEL_SETS
    WHERE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME ) IN
            ( SELECT PGP.PROPERTY_GRAPH_CATALOG, PGP.PROPERTY_GRAPH_SCHEMA, 
                     PGP.PROPERTY_GRAPH_NAME
              FROM DEFINITION_SCHEMA.PG_PROPERTY_GRAPH_PRIVILEGES AS PGP
              WHERE ( PGP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                     OR
                      PGP.GRANTEE IN ( SELECT ROLE_NAME
                                       FROM ENABLED_ROLES ) ) )
       AND
          PROPERTY_GRAPH_CATALOG = ( SELECT CATALOG_NAME
                                     FROM INFORMATION_SCHEMA_CATALOG_NAME );
                                     
GRANT SELECT ON TABLE PG_VERTEX_DEFINED_LABEL_SETS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW PROPERTY_GRAPHS AS
    SELECT PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME
    FROM DEFINITION_SCHEMA.PROPERTY_GRAPHS
    WHERE ( PROPERTY_GRAPH_CATALOG, PROPERTY_GRAPH_SCHEMA, PROPERTY_GRAPH_NAME ) IN
            ( SELECT PGP.PROPERTY_GRAPH_CATALOG, PGP.PROPERTY_GRAPH_SCHEMA, 
                     PGP.PROPERTY_GRAPH_NAME
              FROM DEFINITION_SCHEMA.PG_PROPERTY_GRAPH_PRIVILEGES AS PGP
              WHERE ( PGP.GRANTEE IN ( 'PUBLIC', CURRENT_USER )
                     OR
                      PGP.GRANTEE IN ( SELECT ROLE_NAME
                                       FROM ENABLED_ROLES ) ) )
       AND
          PROPERTY_GRAPH_CATALOG = ( SELECT CATALOG_NAME
                                     FROM INFORMATION_SCHEMA_CATALOG_NAME );
                                     
GRANT SELECT ON TABLE PROPERTY_GRAPHS
    TO PUBLIC WITH GRANT OPTION;
  