
/*
The following material is a "digital artifact" containing a series of complete
or partial SQL "schema definition" and/or "schema manipulation" statements
that effectively create or modify an SQL schema to support the facilities defined in one
part of ISO/IEC 9075. 

These statements may be used by SQL-implementations to create their initial
Information and Definition schemata. 
*/

      
      
/* Definition Schema */
      
CREATE TABLE MODULE_COLUMN_USAGE (
    MODULE_CATALOG      INFORMATION_SCHEMA.SQL_IDENTIFIER,
    MODULE_SCHEMA       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    MODULE_NAME         INFORMATION_SCHEMA.SQL_IDENTIFIER,
    TABLE_CATALOG       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    TABLE_SCHEMA        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    TABLE_NAME          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    COLUMN_NAME         INFORMATION_SCHEMA.SQL_IDENTIFIER,
    CONSTRAINT MODULE_COLUMN_USAGE_PRIMARY_KEY
      PRIMARY KEY ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME,
                    TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME ),
    CONSTRAINT MODULE_COLUMN_USAGE_CHECK_REFERENCES_COLUMNS
      CHECK ( TABLE_CATALOG <>
              ANY ( SELECT CATALOG_NAME
                    FROM SCHEMATA )
          OR
            ( TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME ) IN
              ( SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
                FROM COLUMNS ) ),
    CONSTRAINT MODULE_COLUMN_USAGE_FOREIGN_KEY_MODULE_TABLE_USAGE
      FOREIGN KEY ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME,
                    TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME )
        REFERENCES MODULE_TABLE_USAGE
    )

  
CREATE TABLE MODULE_PRIVILEGES (
      GRANTOR                INFORMATION_SCHEMA.SQL_IDENTIFIER,
      GRANTEE                INFORMATION_SCHEMA.SQL_IDENTIFIER,
      MODULE_CATALOG         INFORMATION_SCHEMA.SQL_IDENTIFIER,
      MODULE_SCHEMA          INFORMATION_SCHEMA.SQL_IDENTIFIER,
      MODULE_NAME            INFORMATION_SCHEMA.SQL_IDENTIFIER,
      PRIVILEGE_TYPE         INFORMATION_SCHEMA.CHARACTER_DATA
        CONSTRAINT MODULE_PRIVILEGES_TYPE_CHECK
          CHECK ( PRIVILEGE_TYPE = 'EXECUTE' ),
      IS_GRANTABLE           INFORMATION_SCHEMA.YES_OR_NO
        CONSTRAINT MODULE_PRIVILEGES_GRANTABLE_NOT_NULL
            NOT NULL,
      CONSTRAINT MODULE_PRIVILEGES_PRIMARY_KEY
        PRIMARY KEY ( GRANTOR, GRANTEE, MODULE_CATALOG, MODULE_SCHEMA,
                      MODULE_NAME ),
      CONSTRAINT MODULE_PRIVILEGES_FOREIGN_KEY_TABLES
        FOREIGN KEY ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME )
          REFERENCES MODULES,
      CONSTRAINT MODULE_PRIVILEGE_GRANTOR_CHECK
        CHECK ( GRANTOR = '_SYSTEM'
              OR
                GRANTOR IN
                ( SELECT AUTHORIZATION_NAME
                  FROM AUTHORIZATIONS ) ),
      CONSTRAINT MODULE_PRIVILEGE_GRANTEE_CHECK
        CHECK ( GRANTEE = 'PUBLIC'
              OR
                GRANTEE IN
                ( SELECT AUTHORIZATION_NAME
                  FROM AUTHORIZATIONS ) )
    )

  
CREATE TABLE MODULE_TABLE_USAGE (
    MODULE_CATALOG      INFORMATION_SCHEMA.SQL_IDENTIFIER,
    MODULE_SCHEMA       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    MODULE_NAME         INFORMATION_SCHEMA.SQL_IDENTIFIER,
    TABLE_CATALOG       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    TABLE_SCHEMA        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    TABLE_NAME          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    CONSTRAINT MODULE_TABLE_USAGE_PRIMARY_KEY
      PRIMARY KEY ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME,
                    TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME ),
    CONSTRAINT MODULE_TABLE_USAGE_CHECK_REFERENCES_TABLES
      CHECK ( TABLE_CATALOG <>
              ANY ( SELECT CATALOG_NAME
                    FROM SCHEMATA )
            OR
              ( TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME ) IN
                ( SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
                  FROM TABLES ) ),
    CONSTRAINT MODULE_TABLE_USAGE_FOREIGN_KEY_MODULES
      FOREIGN KEY ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME )
       REFERENCES MODULES
    )

  
CREATE TABLE MODULES (
    MODULE_CATALOG              INFORMATION_SCHEMA.SQL_IDENTIFIER,
    MODULE_SCHEMA               INFORMATION_SCHEMA.SQL_IDENTIFIER,
    MODULE_NAME                 INFORMATION_SCHEMA.SQL_IDENTIFIER,
    DEFAULT_CHARACTER_SET_CATALOG INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT MODULES_DEFAULT_CHARACTER_SET_CATALOG_NOT_NULL
        NOT NULL,
    DEFAULT_CHARACTER_SET_SCHEMA  INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT MODULES_DEFAULT_CHARACTER_SET_SCHEMA_NOT_NULL
        NOT NULL,
    DEFAULT_CHARACTER_SET_NAME    INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT MODULES_DEFAULT_CHARACTER_SET_NAME_NOT_NULL
        NOT NULL,
    DEFAULT_SCHEMA_CATALOG        INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT MODULES_DEFAULT_SCHEMA_CATALOG_NOT_NULL
        NOT NULL,
    DEFAULT_SCHEMA_NAME           INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT MODULES_DEFAULT_SCHEMA_NAME_NOT_NULL
        NOT NULL,
    MODULE_DEFINITION             INFORMATION_SCHEMA.CHARACTER_DATA,
    MODULE_AUTHORIZATION          INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT AUTHORIZATION_FOREIGN_KEY_AUTHORIZATIONS REFERENCES AUTHORIZATIONS,
    SQL_PATH                      INFORMATION_SCHEMA.CHARACTER_DATA,
    CREATED                       INFORMATION_SCHEMA.TIME_STAMP,
    CONSTRAINT MODULES_PRIMARY_KEY
      PRIMARY KEY ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME ),
    CONSTRAINT MODULES_FOREIGN_KEY_SCHEMATA
      FOREIGN KEY ( MODULE_CATALOG, MODULE_SCHEMA )
        REFERENCES SCHEMATA,
    CONSTRAINT MODULES_FOREIGN_KEY_CHARACTER_SETS
      FOREIGN KEY ( DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA,
                    DEFAULT_CHARACTER_SET_NAME )
        REFERENCES CHARACTER_SETS,
    CONSTRAINT MODULES_FOREIGN_KEY_DEFAULT_SCHEMA_SCHEMATA
      FOREIGN KEY ( DEFAULT_SCHEMA_CATALOG, DEFAULT_SCHEMA_NAME )
        REFERENCES SCHEMATA
    )

  
    ALTER TABLE ROUTINES
      ADD CONSTRAINT ROUTINES_FOREIGN_KEY_MODULES
        FOREIGN KEY ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME )
        REFERENCES MODULES
          MATCH FULL;

  
      
      
/* Information Schema */      
      
CREATE VIEW MODULE_COLUMN_USAGE AS
    SELECT MCU.MODULE_CATALOG, MCU.MODULE_SCHEMA, MCU.MODULE_NAME,
           MCU.TABLE_CATALOG, MCU.TABLE_SCHEMA, MCU.TABLE_NAME, MCU.COLUMN_NAME
    FROM DEFINITION_SCHEMA.MODULE_COLUMN_USAGE AS MCU
      JOIN
         DEFINITION_SCHEMA.SCHEMATA AS S
      ON ( ( MCU.TABLE_CATALOG, MCU.TABLE_SCHEMA ) =
           ( S.CATALOG_NAME, S.SCHEMA_NAME ) )
    WHERE ( S.SCHEMA_OWNER = CURRENT_USER
          OR
            S.SCHEMA_OWNER IN
            ( SELECT ER.ROLE_NAME
              FROM ENABLED_ROLES AS ER ) )
       AND
          MCU.MODULE_CATALOG =
          ( SELECT ISCN.CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME AS ISCN );
            
GRANT SELECT ON TABLE MODULE_COLUMN_USAGE
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW MODULE_PRIVILEGES AS
    SELECT
      GRANTOR, GRANTEE, MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME,
      PRIVILEGE_TYPE, IS_GRANTABLE
    FROM DEFINITION_SCHEMA.MODULE_PRIVILEGES
    WHERE ( GRANTEE IN
            ( 'PUBLIC', CURRENT_USER )
          OR
            GRANTEE IN
              ( SELECT ROLE_NAME
                FROM ENABLED_ROLES )
          OR
            GRANTOR = CURRENT_USER
          OR
            GRANTOR IN
              ( SELECT ROLE_NAME
                FROM ENABLED_ROLES ) )
        AND
          MODULE_CATALOG =
          ( SELECT CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME );
GRANT SELECT ON TABLE MODULE_PRIVILEGES
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW MODULE_TABLE_USAGE AS
    SELECT MTU.MODULE_CATALOG, MTU.MODULE_SCHEMA, MTU.MODULE_NAME,
           MTU.TABLE_CATALOG, MTU.TABLE_SCHEMA, MTU.TABLE_NAME
    FROM DEFINITION_SCHEMA.MODULE_TABLE_USAGE AS MTU
      JOIN
         DEFINITION_SCHEMA.SCHEMATA AS S
      ON ( ( MTU.TABLE_CATALOG, MTU.TABLE_SCHEMA ) =
           ( S.CATALOG_NAME, S.SCHEMA_NAME ) )
    WHERE ( S.SCHEMA_OWNER = CURRENT_USER
          OR
            S.SCHEMA_OWNER IN
            ( SELECT ER.ROLE_NAME
              FROM ENABLED_ROLES AS ER ) )
       AND
          MTU.MODULE_CATALOG =
          ( SELECT ISCN.CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME AS ISCN );
GRANT SELECT ON TABLE MODULE_TABLE_USAGE
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW MODULES AS
    SELECT MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME,
           DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA,
           DEFAULT_CHARACTER_SET_NAME,
           DEFAULT_SCHEMA_CATALOG, DEFAULT_SCHEMA_NAME,
           CASE
             WHEN EXISTS (
               SELECT *
               FROM DEFINITION_SCHEMA.SCHEMATA AS S
               WHERE ( MODULE_CATALOG, MODULE_SCHEMA ) =
                     ( S.CATALOG_NAME, S.SCHEMA_NAME )
                 AND
                     ( S.SCHEMA_OWNER = CURRENT_USER
                   OR
                     S.SCHEMA_OWNER IN
                     ( SELECT ROLE_NAME
                       FROM ENABLED_ROLES ) ) )
             THEN MODULE_DEFINITION
             ELSE NULL
           END AS MODULE_DEFINITION,
           MODULE_AUTHORIZATION, SQL_PATH, CREATED
    FROM DEFINITION_SCHEMA.MODULES
    WHERE ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME ) IN
            ( SELECT MP.MODULE_CATALOG, MP.MODULE_SCHEMA, MP.MODULE_NAME
              FROM DEFINITION_SCHEMA.MODULE_PRIVILEGES AS MP
              WHERE ( MP.GRANTEE IN
                      ( 'PUBLIC', CURRENT_USER )
                  OR
                    MP.GRANTEE IN
                    ( SELECT ROLE_NAME
                      FROM ENABLED_ROLES ) ) )
      AND
          MODULE_CATALOG =
          ( SELECT CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME );
            
GRANT SELECT ON TABLE MODULES
    TO PUBLIC WITH GRANT OPTION;

  
/* Modify the PARAMETERS view by inserting after the text:
     
                          FROM ENABLED_ROLES AS ER ) ) ) )

   the text:
     
          OR
            ( ( R.MODULE_CATALOG, R.MODULE_SCHEMA, R.MODULE_NAME ) IS NOT NULL
            AND
              ( R.MODULE_CATALOG, R.MODULE_SCHEMA, R.MODULE_NAME ) IN
                ( SELECT MP.MODULE_CATALOG, MP.MODULE_SCHEMA, MP.MODULE_NAME
                  FROM DEFINITION_SCHEMA.MODULE_PRIVILEGES AS MP
                  WHERE ( MP.GRANTEE IN
                          ( 'PUBLIC', CURRENT_USER )
                        OR
                          MP.GRANTEE IN
                          ( SELECT ER.ROLE_NAME
                            FROM ENABLED_ROLES AS ER ) ) ) )

*/
    
  
CREATE VIEW ROLE_MODULE_GRANTS AS
    SELECT GRANTOR, GRANTEE, MODULE_CATALOG,
           MODULE_SCHEMA, MODULE_NAME, PRIVILEGE_TYPE,
           IS_GRANTABLE
    FROM DEFINITION_SCHEMA.MODULE_PRIVILEGES
    WHERE ( GRANTEE IN
            ( SELECT ROLE_NAME
              FROM ENABLED_ROLES )
          OR
            GRANTOR IN
            ( SELECT ROLE_NAME
              FROM ENABLED_ROLES ) )
       AND
          MODULE_CATALOG =
          ( SELECT CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME );
GRANT SELECT ON TABLE ROLE_MODULE_GRANTS
    TO PUBLIC WITH GRANT OPTION;

  
/* Modify the ROUTINES view by inserting after the text:
     
    WHERE (

   the text:
     
            ( (

*/
    
  
/* Modify the ROUTINES view by inserting after the text:
     
                            FROM ENABLED_ROLES ) ) )

   the text:
     
                                                     )
          OR
            ( ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME) IS NOT NULL
              AND
              ( MODULE_CATALOG, MODULE_SCHEMA, MODULE_NAME ) IN
                ( SELECT MP.MODULE_CATALOG, MP.MODULE_SCHEMA, MP.MODULE_NAME
                  FROM DEFINITION_SCHEMA.MODULE_PRIVILEGES AS MP
                  WHERE ( MP.GRANTEE IN
                          ( 'PUBLIC', CURRENT_USER )
                        OR
                          MP.GRANTEE IN
                          ( SELECT ROLE_NAME
                            FROM ENABLED_ROLES ) ) ) ) )

*/
    
  