
/*
The following material is a "digital artifact" containing a series of complete
or partial SQL "schema definition" and/or "schema manipulation" statements
that effectively create or modify an SQL schema to support the facilities defined in one
part of ISO/IEC 9075. 

These statements may be used by SQL-implementations to create their initial
Information and Definition schemata. 
*/

      
      
/* Definition Schema */
      
INSERT INTO LANGUAGES_LIST ( LANGUAGE )
    VALUES ('JAVA');

  
INSERT INTO USAGE_OBJECT_TYPES_LIST ( OBJECT_TYPE )
    VALUES ('JAR');

  
INSERT INTO USER_DEFINED_TYPES_ORDERINGS_LIST ( ORDERING_CATEGORY )
    VALUES ('COMPARABLE');

  
CREATE TABLE JAR_JAR_USAGE (
    JAR_CATALOG                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAR_SCHEMA                                   INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAR_NAME                                     INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PATH_JAR_CATALOG                             INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PATH_JAR_SCHEMA                              INFORMATION_SCHEMA.SQL_IDENTIFIER,
    PATH_JAR_NAME                                INFORMATION_SCHEMA.SQL_IDENTIFIER,

    CONSTRAINT JAR_JAR_USAGE_PRIMARY_KEY
      PRIMARY KEY ( JAR_CATALOG, JAR_SCHEMA, JAR_NAME,
                    PATH_JAR_CATALOG, PATH_JAR_SCHEMA, PATH_JAR_NAME ),

    CONSTRAINT JAR_JAR_USAGE_CHECK_REFERENCES_JARS
      CHECK ( PATH_JAR_CATALOG NOT IN
              ( SELECT CATALOG_NAME
                FROM SCHEMATA )
            OR
              ( PATH_JAR_CATALOG, PATH_JAR_SCHEMA, PATH_JAR_NAME ) IN
              ( SELECT JAR_CATALOG, JAR_SCHEMA, JAR_NAME
                FROM JARS ) ),

    CONSTRAINT JAR_JAR_USAGE_FOREIGN_KEY_JARS
      FOREIGN KEY ( JAR_CATALOG, JAR_SCHEMA, JAR_NAME )
        REFERENCES JARS
    );

  
CREATE TABLE JARS (
    JAR_CATALOG                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAR_SCHEMA                                   INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAR_NAME                                     INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAVA_PATH                                    INFORMATION_SCHEMA.CHARACTER_DATA,

    CONSTRAINT JARS_PRIMARY_KEY
      PRIMARY KEY ( JAR_CATALOG, JAR_SCHEMA, JAR_NAME ),
    CONSTRAINT JAR_FOREIGN_KEY_SCHEMATA
      FOREIGN KEY ( JAR_CATALOG, JAR_SCHEMA )
        REFERENCES SCHEMATA
    );

  
ALTER TABLE METHOD_SPECIFICATIONS
    ADD COLUMN EXTERNAL_NAME            INFORMATION_SCHEMA.CHARACTER_DATA;

ALTER TABLE METHOD_SPECIFICATIONS
    ADD COLUMN IS_FIELD                 INFORMATION_SCHEMA.YES_OR_NO;

ALTER TABLE METHOD_SPECIFICATIONS
    ADD CONSTRAINT METHOD_SPECIFICATIONS_METHOD_COMBINATIONS
      CHECK ( ( ( METHOD_LANGUAGE = 'JAVA' )
             AND
                ( EXTERNAL_NAME, IS_FIELD ) IS NOT NULL )
            OR
              ( ( METHOD_LANGUAGE <> 'JAVA' )
             AND
                ( ( EXTERNAL_NAME, IS_FIELD )
                IS NULL ) ) );

ALTER TABLE METHOD_SPECIFICATIONS
    ADD CONSTRAINT METHOD_SPECIFICATIONS_FIELD_COMBINATIONS
      CHECK ( IS_FIELD = 'NO' OR IS_STATIC = 'YES' );

  
CREATE TABLE ROUTINE_JAR_USAGE (
    SPECIFIC_CATALOG                             INFORMATION_SCHEMA.SQL_IDENTIFIER,
    SPECIFIC_SCHEMA                              INFORMATION_SCHEMA.SQL_IDENTIFIER,
    SPECIFIC_NAME                                INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAR_CATALOG                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAR_SCHEMA                                   INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAR_NAME                                     INFORMATION_SCHEMA.SQL_IDENTIFIER,

    CONSTRAINT ROUTINE_JAR_USAGE_PRIMARY_KEY
      PRIMARY KEY ( SPECIFIC_CATALOG, SPECIFIC_SCHEMA, SPECIFIC_NAME,
                    JAR_CATALOG, JAR_SCHEMA, JAR_NAME ),

    CONSTRAINT JAR_JAR_USAGE_CHECK_REFERENCES_JARS
      CHECK ( JAR_CATALOG NOT IN
              ( SELECT CATALOG_NAME
                FROM SCHEMATA )
            OR
              ( JAR_CATALOG, JAR_SCHEMA, JAR_NAME ) IN
              ( SELECT JAR_CATALOG, JAR_SCHEMA, JAR_NAME
                FROM JARS ) ),

    CONSTRAINT JAR_JAR_USAGE_FOREIGN_KEY_ROUTINES
      FOREIGN KEY (SPECIFIC_CATALOG, SPECIFIC_SCHEMA, SPECIFIC_NAME )
        REFERENCES ROUTINES
    );

  
CREATE TABLE TYPE_JAR_USAGE (
    USER_DEFINED_TYPE_CATALOG                    INFORMATION_SCHEMA.SQL_IDENTIFIER,
    USER_DEFINED_TYPE_SCHEMA                     INFORMATION_SCHEMA.SQL_IDENTIFIER,
    USER_DEFINED_TYPE_NAME                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAR_CATALOG                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAR_SCHEMA                                   INFORMATION_SCHEMA.SQL_IDENTIFIER,
    JAR_NAME                                     INFORMATION_SCHEMA.SQL_IDENTIFIER,

    CONSTRAINT TYPE_JAR_USAGE_PRIMARY_KEY
      PRIMARY KEY (USER_DEFINED_TYPE_CATALOG, USER_DEFINED_TYPE_SCHEMA,
                   USER_DEFINED_TYPE_NAME, JAR_CATALOG, JAR_SCHEMA, JAR_NAME),

    CONSTRAINT TYPE_JAR_USAGE_CHECK_REFERENCES_JARS
      CHECK ( JAR_CATALOG NOT IN
              ( SELECT CATALOG_NAME
                FROM SCHEMATA )
            OR
              ( JAR_CATALOG, JAR_SCHEMA, JAR_NAME ) IN
              ( SELECT JAR_CATALOG, JAR_SCHEMA, JAR_NAME
                FROM JARS ) ),

    CONSTRAINT TYPE_JAR_USAGE_FOREIGN_KEY_USER_DEFINED_TYPES
      FOREIGN KEY (USER_DEFINED_TYPE_CATALOG, USER_DEFINED_TYPE_SCHEMA,
                   USER_DEFINED_TYPE_NAME ) REFERENCES USER_DEFINED_TYPES
    );

  
ALTER TABLE USAGE_PRIVILEGES
    ADD CONSTRAINT USAGE_PRIVILEGES_CHECK_REFERENCES_JARS
        CHECK ( OBJECT_TYPE <> 'JAR'
            OR
             ( OBJECT_CATALOG, OBJECT_SCHEMA, OBJECT_NAME) IN
             ( SELECT JAR_CATALOG, JAR_SCHEMA, JAR_NAME
               FROM JARS);

  
ALTER TABLE USER_DEFINED_TYPES
    ADD COLUMN EXTERNAL_NAME                      INFORMATION_SCHEMA.CHARACTER_DATA;

ALTER TABLE USER_DEFINED_TYPES
    ADD COLUMN EXTERNAL_LANGUAGE                  INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT USER_DEFINED_TYPE_EXTERNAL_LANGUAGE_CHECK
        CHECK ( EXTERNAL_LANGUAGE IN ( 'JAVA' ) );

ALTER TABLE USER_DEFINED_TYPES
    ADD COLUMN     JAVA_INTERFACE                 INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT USER_DEFINED_TYPE_JAVA_INTERFACE_CHECK
        CHECK ( JAVA_INTERFACE IN ( 'SERIALIZABLE', 'SQLDATA' ) );


 ALTER TABLE USER_DEFINED_TYPES
    ADD CONSTRAINT USER_DEFINED_TYPES_COMBINATIONS
      CHECK ( ( ( EXTERNAL_LANGUAGE = 'JAVA' ) AND
                ( EXTERNAL_NAME, JAVA_INTERFACE ) IS NOT NULL )
          OR
            ( ( EXTERNAL_LANGUAGE, EXTERNAL_NAME, JAVA_INTERFACE )
              IS NULL ) );

  
      
      
/* Information Schema */      
      
CREATE VIEW JAR_JAR_USAGE AS
    SELECT JJU.PATH_JAR_CATALOG, JJU.PATH_JAR_SCHEMA, JJU.PATH_JAR_NAME,
           JAR_CATALOG, JAR_SCHEMA, JAR_NAME
    FROM ( DEFINITION_SCHEMA.JAR_JAR_USAGE AS JJU
        JOIN
           DEFINITION_SCHEMA.JARS AS J
        USING ( JAR_CATALOG, JAR_SCHEMA, JAR_NAME ) )
      JOIN
         DEFINITION_SCHEMA.SCHEMATA AS S
      ON ( ( JJU.PATH_JAR_CATALOG, JJU.PATH_JAR_SCHEMA )
         = ( S.CATALOG_NAME, S.SCHEMA_NAME ) )
    WHERE ( S.SCHEMA_OWNER = CURRENT_USER
          OR
            S.SCHEMA_OWNER IN
            ( SELECT ER.ROLE_NAME
              FROM ENABLED_ROLES AS ER ) )
       AND
          JAR_CATALOG =
          ( SELECT ISCN.CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME AS ISCN ) ;
            
GRANT SELECT ON TABLE JAR_JAR_USAGE
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW JARS AS
    SELECT JAR_CATALOG, JAR_SCHEMA, JAR_NAME, JAVA_PATH
    FROM DEFINITION_SCHEMA.JARS
    WHERE ( JAR_CATALOG, JAR_SCHEMA, JAR_NAME, 'JAR' ) IN
          ( SELECT OBJECT_CATALOG, OBJECT_SCHEMA, OBJECT_NAME, OBJECT_TYPE
            FROM DEFINITION_SCHEMA.USAGE_PRIVILEGES
            WHERE GRANTEE IN
                  ( 'PUBLIC', CURRENT_USER )
                OR
                  GRANTEE IN
                  ( SELECT ROLE_NAME
                    FROM ENABLED_ROLES ) )
       AND
          JAR_CATALOG =
          ( SELECT CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME ) ;
            
GRANT SELECT ON TABLE JARS
    TO PUBLIC WITH GRANT OPTION;

  
/* Modify the METHOD_SPECIFICATIONS view by inserting after the text:
     
           D.DECLARED_DATA_TYPE, D.DECLARED_NUMERIC_PRECISION,
           D.DECLARED_NUMERIC_SCALE

   the text:
     
, EXTERNAL_NAME, IS_FIELD

*/
    
  
CREATE VIEW ROUTINE_JAR_USAGE AS
    SELECT SPECIFIC_CATALOG, SPECIFIC_SCHEMA, SPECIFIC_NAME,
           RJU.JAR_CATALOG, RJU.JAR_SCHEMA, RJU.JAR_NAME
    FROM ( DEFINITION_SCHEMA.ROUTINE_JAR_USAGE AS RJU
        JOIN
           DEFINITION_SCHEMA.ROUTINES AS R
        USING ( SPECIFIC_CATALOG, SPECIFIC_SCHEMA, SPECIFIC_NAME ) )
      JOIN
         DEFINITION_SCHEMA.SCHEMATA AS S
      ON ( ( RJU.JAR_CATALOG, RJU.JAR_SCHEMA ) =
           ( S.CATALOG_NAME, S.SCHEMA_NAME ) )
    WHERE ( S.SCHEMA_OWNER = CURRENT_USER
          OR
            S.SCHEMA_OWNER IN
            ( SELECT ER.ROLE_NAME
              FROM ENABLED_ROLES AS ER ) )
       AND
          SPECIFIC_CATALOG =
          ( SELECT ISCN.CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME AS ISCN ) ;
            
GRANT SELECT ON TABLE ROUTINE_JAR_USAGE
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW TYPE_JAR_USAGE AS
    SELECT USER_DEFINED_TYPE_CATALOG AS UDT_CATALOG,
           USER_DEFINED_TYPE_SCHEMA AS UDT_SCHEMA,
           USER_DEFINED_TYPE_NAME AS UDT_NAME,
           TJU.JAR_CATALOG, TJU.JAR_SCHEMA, TJU.JAR_NAME
    FROM ( DEFINITION_SCHEMA.TYPE_JAR_USAGE AS TJU
        JOIN
           DEFINITION_SCHEMA.USER_DEFINED_TYPES AS UDT
        USING ( USER_DEFINED_TYPE_CATALOG, USER_DEFINED_TYPE_SCHEMA,
                USER_DEFINED_TYPE_NAME ) )
      JOIN
         DEFINITION_SCHEMA.SCHEMATA AS S
      ON ( ( TJU.JAR_CATALOG, TJU.JAR_SCHEMA ) =
           ( S.CATALOG_NAME, S.SCHEMA_NAME ) )
    WHERE ( S.SCHEMA_OWNER = CURRENT_USER
          OR
            S.SCHEMA_OWNER IN
            ( SELECT ER.ROLE_NAME
              FROM ENABLED_ROLES AS ER ) )
       AND
          USER_DEFINED_TYPE_CATALOG =
          ( SELECT ISCN.CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME AS ISCN ) ;
            
GRANT SELECT ON TABLE TYPE_JAR_USAGE
    TO PUBLIC WITH GRANT OPTION;

  
/* Modify the USER_DEFINED_TYPES view by inserting after the text:
     
           DTD.DECLARED_DATA_TYPE, DTD.DECLARED_NUMERIC_PRECISION,
           DTD.DECLARED_NUMERIC_SCALE, DTD.MAXIMUM_CARDINALITY

   the text:
     
, EXTERNAL_NAME, EXTERNAL_LANGUAGE, JAVA_INTERFACE

*/
    
  