
/*
The following material is a "digital artifact" containing a series of complete
or partial SQL "schema definition" and/or "schema manipulation" statements
that effectively create or modify an SQL schema to support the facilities defined in one
part of ISO/IEC 9075. 

These statements may be used by SQL-implementations to create their initial
Information and Definition schemata. 
*/

      
      
/* Definition Schema */
      
INSERT INTO DATA_TYPES_LIST ( DATA_TYPE )
    VALUES ('MDARRAY');

  
INSERT INTO COLLECTION_TYPES_LIST ( COLLECTION_TYPE )
    VALUES ('MDARRAY');

  
CREATE TABLE MD_EXTENTS (
    OBJECT_CATALOG                               INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OBJECT_SCHEMA                                INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OBJECT_NAME                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OBJECT_TYPE                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    MDARRAY_IDENTIFIER                           INFORMATION_SCHEMA.SQL_IDENTIFIER,
    MD_AXIS_NAME                                 INFORMATION_SCHEMA.SQL_IDENTIFIER,
    MD_AXIS_LO                                   INFORMATION_SCHEMA.CHARACTER_DATA,
    MD_AXIS_HI                                   INFORMATION_SCHEMA.CHARACTER_DATA,
    ORDINAL_POSITION                             INFORMATION_SCHEMA.CARDINAL_NUMBER,
      CONSTRAINT MD_EXTENTS_ORDINAL_POSITION_NOT_NULL
        NOT NULL
      CONSTRAINT MD_EXTENTS_ORDINAL_POSITION_GREATER_THAN_ZERO_CHECK
        CHECK ( ORDINAL_POSITION > 0 )
      CONSTRAINT MD_EXTENTS_ORDINAL_POSITION_CONTIGUOUS_CHECK
        CHECK ( 0 = ALL ( SELECT MAX(ORDINAL_POSITION) - COUNT(*)
                          FROM MD_EXTENTS
                          GROUP BY OBJECT_CATALOG, OBJECT_SCHEMA, OBJECT_NAME,
                                   OBJECT_TYPE, MDARRAY_IDENTIFIER ) ),

    CONSTRAINT MD_EXTENTS_PRIMARY_KEY
      PRIMARY KEY ( OBJECT_CATALOG, OBJECT_SCHEMA, OBJECT_NAME,
                    OBJECT_TYPE, MDARRAY_IDENTIFIER, MD_AXIS_NAME ),

    CONSTRAINT MD_EXTENTS_UNIQUE
      UNIQUE ( OBJECT_CATALOG, OBJECT_SCHEMA, OBJECT_NAME,
               OBJECT_TYPE, MDARRAY_IDENTIFIER, ORDINAL_POSITION ),

    CONSTRAINT MD_EXTENTS_CHECK_MDARRAY_TYPE
      CHECK (
        ( OBJECT_CATALOG, OBJECT_SCHEMA, OBJECT_NAME,
          OBJECT_TYPE, MDARRAY_IDENTIFIER ) IN
        ( SELECT OBJECT_CATALOG, OBJECT_SCHEMA, OBJECT_NAME,
                 OBJECT_TYPE, DTD_IDENTIFIER
          FROM DATA_TYPE_DESCRIPTOR
          WHERE DATA_TYPE = 'MDARRAY') ),

    CONSTRAINT MD_EXTENTS_MD_AXIS_LIMITS_CHECK
      CHECK ( CAST ( MD_AXIS_HI AS BIGINT ) >=
             CAST ( MD_AXIS_LO AS BIGINT ) )
    );

  
      
      
/* Information Schema */      
      
CREATE VIEW MD_EXTENTS AS
    SELECT
        MDE.OBJECT_CATALOG, MDE.OBJECT_SCHEMA, MDE.OBJECT_NAME,
        MDE.OBJECT_TYPE, MDE.MDARRAY_IDENTIFIER,
        MDE.MD_AXIS_NAME, MDE.MD_AXIS_LO, MDE.MD_AXIS_HI,
        MDE.ORDINAL_POSITION
    FROM DEFINITION_SCHEMA.MD_EXTENTS AS MDE
    WHERE ( MDE.OBJECT_CATALOG, MDE.OBJECT_SCHEMA, MDE.OBJECT_NAME,
            MDE.OBJECT_TYPE, MDE.MDARRAY_IDENTIFIER ) IN
          ( SELECT ET.OBJECT_CATALOG, ET.OBJECT_SCHEMA, ET.OBJECT_NAME,
                   ET.OBJECT_TYPE, ET.DTD_IDENTIFIER
            FROM DEFINITION_SCHEMA.ELEMENT_TYPES AS ET
            WHERE ( ET.OBJECT_CATALOG, ET.OBJECT_SCHEMA, ET.OBJECT_NAME,
                    ET.OBJECT_TYPE, ET.ROOT_DTD_IDENTIFIER ) IN
                  ( SELECT DTP.OBJECT_CATALOG, DTP.OBJECT_SCHEMA, DTP.OBJECT_NAME,
                           DTP.OBJECT_TYPE, DTP.DTD_IDENTIFIER
                    FROM INFORMATION_SCHEMA.DATA_TYPE_PRIVILEGES AS DTP ) );

GRANT SELECT ON TABLE MD_EXTENTS
TO PUBLIC WITH GRANT OPTION;

  