
-- The following Ada package, Interfaces.SQL, is a "digital artifact" that contains
-- lines of code in the Ada programming language.  These lines of code define an Ada package
-- that defines several Ada types and a contained package that defines Ada symbols representing
-- all condition codes associated with all conditions that may be raised by an SQL-implementation
-- when evaluating SQL expressions and executing SQL statements. 

-- It may be used in Ada application programs that access SQL-implementations.

package Interfaces.SQL is
-- The declarations of CHAR and NCHAR may be subtype declarations
  type CHAR is                         -- (See the Syntax Rules)
  type NCHAR is                        -- (See the Syntax Rules)
  type SMALLINT is range bs .. ts;
  type INT is range bi .. ti;
  type BIGINT is range bb .. tb;
  type REAL is digits dr;
  type DOUBLE_PRECISION is digits dd;
  type BOOLEAN is new Boolean;
  subtype INDICATOR_TYPE is t;
  type SQLSTATE_TYPE is new CHAR (1 .. 5);
  package SQLSTATE_CODES is
    SUCCESSFUL_COMPLETION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "00000";
    WARNING_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "01000";
    WARNING_CURSOR_OPERATION_CONFLICT:
      constant SQLSTATE_TYPE := "01001";
    WARNING_DISCONNECT_ERROR:
      constant SQLSTATE_TYPE := "01002";
    WARNING_NULL_VALUE_ELIMINATED_IN_SET_FUNCTION:
      constant SQLSTATE_TYPE := "01003";
    WARNING_STRING_DATA_RIGHT_TRUNCATION:
      constant SQLSTATE_TYPE := "01004";
    WARNING_INSUFFICIENT_ITEM_DESCRIPTOR_AREAS:
      constant SQLSTATE_TYPE := "01005";
    WARNING_PRIVILEGE_NOT_REVOKED:
      constant SQLSTATE_TYPE := "01006";
    WARNING_PRIVILEGE_NOT_GRANTED:
      constant SQLSTATE_TYPE := "01007";
    WARNING_SEARCH_CONDITION_TOO_LONG_FOR_INFORMATION_SCHEMA:
      constant SQLSTATE_TYPE := "01009";
    WARNING_QUERY_EXPRESSION_TOO_LONG_FOR_INFORMATION_SCHEMA:
      constant SQLSTATE_TYPE := "0100A";
    WARNING_DEFAULT_VALUE_TOO_LONG_FOR_INFORMATION_SCHEMA:
      constant SQLSTATE_TYPE := "0100B";
    WARNING_RESULT_SETS_RETURNED:
      constant SQLSTATE_TYPE := "0100C";
    WARNING_ATTEMPT_TO_RETURN_TOO_MANY_RESULT_SETS:
      constant SQLSTATE_TYPE := "0100E";
    WARNING_STATEMENT_TOO_LONG_FOR_INFORMATION_SCHEMA:
      constant SQLSTATE_TYPE := "0100F";
    WARNING_INVALID_NUMBER_OF_CONDITIONS:
      constant SQLSTATE_TYPE := "01012";
    WARNING_ARRAY_DATA_RIGHT_TRUNCATION:
      constant SQLSTATE_TYPE := "0102F";
    NO_DATA_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "02000";
    NO_DATA_NO_ADDITIONAL_RESULT_SETS_RETURNED:
      constant SQLSTATE_TYPE := "02001";
    DYNAMIC_SQL_ERROR_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "07000";
    DYNAMIC_SQL_ERROR_USING_CLAUSE_DOES_NOT_MATCH_DYNAMIC_PARAMETER_SPECIFICATIONS:
      constant SQLSTATE_TYPE := "07001";
    DYNAMIC_SQL_ERROR_USING_CLAUSE_DOES_NOT_MATCH_TARGET_SPECIFICATIONS:
      constant SQLSTATE_TYPE := "07002";
    DYNAMIC_SQL_ERROR_CURSOR_SPECIFICATION_CANNOT_BE_EXECUTED:
      constant SQLSTATE_TYPE := "07003";
    DYNAMIC_SQL_ERROR_USING_CLAUSE_REQUIRED_FOR_DYNAMIC_PARAMETERS:
      constant SQLSTATE_TYPE := "07004";
    DYNAMIC_SQL_ERROR_PREPARED_STATEMENT_NOT_A_CURSOR_SPECIFICATION:
      constant SQLSTATE_TYPE := "07005";
    DYNAMIC_SQL_ERROR_RESTRICTED_DATA_TYPE_ATTRIBUTE_VIOLATION:
      constant SQLSTATE_TYPE := "07006";
    DYNAMIC_SQL_ERROR_USING_CLAUSE_REQUIRED_FOR_RESULT_FIELDS:
      constant SQLSTATE_TYPE := "07007";
    DYNAMIC_SQL_ERROR_INVALID_DESCRIPTOR_COUNT:
      constant SQLSTATE_TYPE := "07008";
    DYNAMIC_SQL_ERROR_INVALID_DESCRIPTOR_INDEX:
      constant SQLSTATE_TYPE := "07009";
    DYNAMIC_SQL_ERROR_DATA_TYPE_TRANSFORM_FUNCTION_VIOLATION:
      constant SQLSTATE_TYPE := "0700B";
    DYNAMIC_SQL_ERROR_UNDEFINED_DATA_VALUE:
      constant SQLSTATE_TYPE := "0700C";
    DYNAMIC_SQL_ERROR_INVALID_DATA_TARGET:
      constant SQLSTATE_TYPE := "0700D";
    DYNAMIC_SQL_ERROR_INVALID_LEVEL_VALUE:
      constant SQLSTATE_TYPE := "0700E";
    DYNAMIC_SQL_ERROR_INVALID_DATETIME_INTERVAL_CODE:
      constant SQLSTATE_TYPE := "0700F";
    DYNAMIC_SQL_ERROR_INVALID_PASS_THROUGH_SURROGATE_VALUE:
      constant SQLSTATE_TYPE := "0700G";
    DYNAMIC_SQL_ERROR_PIPE_ROW_NOT_DURING_PTF_EXECUTION:
      constant SQLSTATE_TYPE := "0700H";
    CONNECTION_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "08000";
    CONNECTION_EXCEPTION_SQL_CLIENT_UNABLE_TO_ESTABLISH_SQL_CONNECTION:
      constant SQLSTATE_TYPE := "08001";
    CONNECTION_EXCEPTION_CONNECTION_NAME_IN_USE:
      constant SQLSTATE_TYPE := "08002";
    CONNECTION_EXCEPTION_CONNECTION_DOES_NOT_EXIST:
      constant SQLSTATE_TYPE := "08003";
    CONNECTION_EXCEPTION_SQL_SERVER_REJECTED_ESTABLISHMENT_OF_SQL_CONNECTION:
      constant SQLSTATE_TYPE := "08004";
    CONNECTION_EXCEPTION_CONNECTION_FAILURE:
      constant SQLSTATE_TYPE := "08006";
    CONNECTION_EXCEPTION_TRANSACTION_RESOLUTION_UNKNOWN:
      constant SQLSTATE_TYPE := "08007";
    TRIGGERED_ACTION_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "09000";
    FEATURE_NOT_SUPPORTED_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0A000";
    FEATURE_NOT_SUPPORTED_MULTIPLE_SERVER_TRANSACTIONS:
      constant SQLSTATE_TYPE := "0A001";
    INVALID_TARGET_TYPE_SPECIFICATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0D000";
    INVALID_SCHEMA_NAME_LIST_SPECIFICATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0E000";
    LOCATOR_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0F000";
    LOCATOR_EXCEPTION_INVALID_SPECIFICATION:
      constant SQLSTATE_TYPE := "0F001";
    INVALID_SQL_INVOKED_PROCEDURE_REFERENCE_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0M000";
    INVALID_ROLE_SPECIFICATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0P000";
    INVALID_TRANSFORM_GROUP_NAME_SPECIFICATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0S000";
    TARGET_TABLE_DISAGREES_WITH_CURSOR_SPECIFICATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0T000";
    ATTEMPT_TO_ASSIGN_TO_NON_UPDATABLE_COLUMN_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0U000";
    ATTEMPT_TO_ASSIGN_TO_ORDERING_COLUMN_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0V000";
    PROHIBITED_STATEMENT_ENCOUNTERED_DURING_TRIGGER_EXECUTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0W000";
    PROHIBITED_STATEMENT_ENCOUNTERED_DURING_TRIGGER_EXECUTION_MODIFY_TABLE_MODIFIED_BY_DATA_CHANGE_DELTA_TABLE:
      constant SQLSTATE_TYPE := "0W001";
    DIAGNOSTICS_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0Z000";
    DIAGNOSTICS_EXCEPTION_MAXIMUM_NUMBER_OF_STACKED_DIAGNOSTICS_AREAS_EXCEEDED:
      constant SQLSTATE_TYPE := "0Z001";
    PROHIBITED_COLUMN_REFERENCE_ENCOUNTERED_DURING_TRIGGER_EXECUTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "11000";
    CARDINALITY_VIOLATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "21000";
    DATA_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "22000";
    DATA_EXCEPTION_STRING_DATA_RIGHT_TRUNCATION:
      constant SQLSTATE_TYPE := "22001";
    DATA_EXCEPTION_NULL_VALUE_NO_INDICATOR_PARAMETER:
      constant SQLSTATE_TYPE := "22002";
    DATA_EXCEPTION_NUMERIC_VALUE_OUT_OF_RANGE:
      constant SQLSTATE_TYPE := "22003";
    DATA_EXCEPTION_NULL_VALUE_NOT_ALLOWED:
      constant SQLSTATE_TYPE := "22004";
    DATA_EXCEPTION_ERROR_IN_ASSIGNMENT:
      constant SQLSTATE_TYPE := "22005";
    DATA_EXCEPTION_INVALID_INTERVAL_FORMAT:
      constant SQLSTATE_TYPE := "22006";
    DATA_EXCEPTION_INVALID_DATE_TIME_OR_DATETIME_FORMAT:
      constant SQLSTATE_TYPE := "22007";
    DATA_EXCEPTION_DATETIME_FIELD_OVERFLOW:
      constant SQLSTATE_TYPE := "22008";
    DATA_EXCEPTION_INVALID_TIME_ZONE_DISPLACEMENT_VALUE:
      constant SQLSTATE_TYPE := "22009";
    DATA_EXCEPTION_ESCAPE_CHARACTER_CONFLICT:
      constant SQLSTATE_TYPE := "2200B";
    DATA_EXCEPTION_INVALID_USE_OF_ESCAPE_CHARACTER:
      constant SQLSTATE_TYPE := "2200C";
    DATA_EXCEPTION_INVALID_ESCAPE_OCTET:
      constant SQLSTATE_TYPE := "2200D";
    DATA_EXCEPTION_NULL_VALUE_IN_ARRAY_TARGET:
      constant SQLSTATE_TYPE := "2200E";
    DATA_EXCEPTION_ZERO_LENGTH_CHARACTER_STRING:
      constant SQLSTATE_TYPE := "2200F";
    DATA_EXCEPTION_MOST_SPECIFIC_TYPE_MISMATCH:
      constant SQLSTATE_TYPE := "2200G";
    DATA_EXCEPTION_SEQUENCE_GENERATOR_LIMIT_EXCEEDED:
      constant SQLSTATE_TYPE := "2200H";
    DATA_EXCEPTION_INTERVAL_VALUE_OUT_OF_RANGE:
      constant SQLSTATE_TYPE := "2200P";
    DATA_EXCEPTION_MULTISET_VALUE_OVERFLOW:
      constant SQLSTATE_TYPE := "2200Q";
    DATA_EXCEPTION_INVALID_INDICATOR_PARAMETER_VALUE:
      constant SQLSTATE_TYPE := "22010";
    DATA_EXCEPTION_SUBSTRING_ERROR:
      constant SQLSTATE_TYPE := "22011";
    DATA_EXCEPTION_DIVISION_BY_ZERO:
      constant SQLSTATE_TYPE := "22012";
    DATA_EXCEPTION_INVALID_PRECEDING_OR_FOLLOWING_SIZE_IN_WINDOW_FUNCTION:
      constant SQLSTATE_TYPE := "22013";
    DATA_EXCEPTION_INVALID_ARGUMENT_FOR_NTILE_FUNCTION:
      constant SQLSTATE_TYPE := "22014";
    DATA_EXCEPTION_INTERVAL_FIELD_OVERFLOW:
      constant SQLSTATE_TYPE := "22015";
    DATA_EXCEPTION_INVALID_ARGUMENT_FOR_NTH_VALUE_FUNCTION:
      constant SQLSTATE_TYPE := "22016";
    DATA_EXCEPTION_INVALID_CHARACTER_VALUE_FOR_CAST:
      constant SQLSTATE_TYPE := "22018";
    DATA_EXCEPTION_INVALID_ESCAPE_CHARACTER:
      constant SQLSTATE_TYPE := "22019";
    DATA_EXCEPTION_INVALID_REGULAR_EXPRESSION:
      constant SQLSTATE_TYPE := "2201B";
    DATA_EXCEPTION_NULL_ROW_NOT_PERMITTED_IN_TABLE:
      constant SQLSTATE_TYPE := "2201C";
    DATA_EXCEPTION_INVALID_ARGUMENT_FOR_NATURAL_LOGARITHM:
      constant SQLSTATE_TYPE := "2201E";
    DATA_EXCEPTION_INVALID_ARGUMENT_FOR_POWER_FUNCTION:
      constant SQLSTATE_TYPE := "2201F";
    DATA_EXCEPTION_INVALID_ARGUMENT_FOR_WIDTH_BUCKET_FUNCTION:
      constant SQLSTATE_TYPE := "2201G";
    DATA_EXCEPTION_INVALID_ROW_VERSION:
      constant SQLSTATE_TYPE := "2201H";
    DATA_EXCEPTION_INVALID_XQUERY_REGULAR_EXPRESSION:
      constant SQLSTATE_TYPE := "2201S";
    DATA_EXCEPTION_INVALID_XQUERY_OPTION_FLAG:
      constant SQLSTATE_TYPE := "2201T";
    DATA_EXCEPTION_ATTEMPT_TO_REPLACE_A_ZERO_LENGTH_STRING:
      constant SQLSTATE_TYPE := "2201U";
    DATA_EXCEPTION_INVALID_XQUERY_REPLACEMENT_STRING:
      constant SQLSTATE_TYPE := "2201V";
    DATA_EXCEPTION_INVALID_ROW_COUNT_IN_FETCH_FIRST_CLAUSE:
      constant SQLSTATE_TYPE := "2201W";
    DATA_EXCEPTION_INVALID_ROW_COUNT_IN_RESULT_OFFSET_CLAUSE:
      constant SQLSTATE_TYPE := "2201X";
    DATA_EXCEPTION_ZERO_LENGTH_BINARY_STRING:
      constant SQLSTATE_TYPE := "2201Y";
    DATA_EXCEPTION_INVALID_ARGUMENT_FOR_GENERAL_LOGARITHM_FUNCTION:
      constant SQLSTATE_TYPE := "2201Z";
    DATA_EXCEPTION_INVALID_PERIOD_VALUE:
      constant SQLSTATE_TYPE := "22020";
    DATA_EXCEPTION_CHARACTER_NOT_IN_REPERTOIRE:
      constant SQLSTATE_TYPE := "22021";
    DATA_EXCEPTION_INDICATOR_OVERFLOW:
      constant SQLSTATE_TYPE := "22022";
    DATA_EXCEPTION_INVALID_PARAMETER_VALUE:
      constant SQLSTATE_TYPE := "22023";
    DATA_EXCEPTION_UNTERMINATED_C_STRING:
      constant SQLSTATE_TYPE := "22024";
    DATA_EXCEPTION_INVALID_ESCAPE_SEQUENCE:
      constant SQLSTATE_TYPE := "22025";
    DATA_EXCEPTION_TRIM_ERROR:
      constant SQLSTATE_TYPE := "22027";
    DATA_EXCEPTION_NON_CHARACTER_IN_CHARACTER_STRING:
      constant SQLSTATE_TYPE := "22029";
    DATA_EXCEPTION_INVALID_VECTOR_VALUE:
      constant SQLSTATE_TYPE := "2202B";
    DATA_EXCEPTION_VECTOR_COORDINATE_NULL_VALUE_NOT_ALLOWED:
      constant SQLSTATE_TYPE := "2202C";
    DATA_EXCEPTION_NULL_VALUE_SUBSTITUTED_FOR_MUTATOR_SUBJECT_PARAMETER:
      constant SQLSTATE_TYPE := "2202D";
    DATA_EXCEPTION_ARRAY_ELEMENT_ERROR:
      constant SQLSTATE_TYPE := "2202E";
    DATA_EXCEPTION_ARRAY_DATA_RIGHT_TRUNCATION:
      constant SQLSTATE_TYPE := "2202F";
    DATA_EXCEPTION_INVALID_REPEAT_ARGUMENT_IN_A_SAMPLE_CLAUSE:
      constant SQLSTATE_TYPE := "2202G";
    DATA_EXCEPTION_INVALID_SAMPLE_SIZE:
      constant SQLSTATE_TYPE := "2202H";
    DATA_EXCEPTION_INVALID_ARGUMENT_FOR_ROW_PATTERN_NAVIGATION_FUNCTION:
      constant SQLSTATE_TYPE := "2202J";
    DATA_EXCEPTION_SKIP_TO_NON_EXISTENT_ROW:
      constant SQLSTATE_TYPE := "2202K";
    DATA_EXCEPTION_SKIP_TO_FIRST_ROW_OF_MATCH:
      constant SQLSTATE_TYPE := "2202L";
    DATA_EXCEPTION_INVALID_ARGUMENT_FOR_TRIGONOMETRIC_FUNCTION:
      constant SQLSTATE_TYPE := "2202M";
    DATA_EXCEPTION_INVALID_ARGUMENT_FOR_INVERSE_DISTRIBUTION_FUNCTION:
      constant SQLSTATE_TYPE := "2202N";
    DATA_EXCEPTION_NON_BOOLEAN_SQL_JSON_ITEM:
      constant SQLSTATE_TYPE := "2202V";
    DATA_EXCEPTION_NON_DATE_SQL_JSON_ITEM:
      constant SQLSTATE_TYPE := "2202W";
    DATA_EXCEPTION_NON_STRING_SQL_JSON_ITEM:
      constant SQLSTATE_TYPE := "2202X";
    DATA_EXCEPTION_NON_TIME_SQL_JSON_ITEM:
      constant SQLSTATE_TYPE := "2202Y";
    DATA_EXCEPTION_NON_TIMESTAMP_SQL_JSON_ITEM:
      constant SQLSTATE_TYPE := "2202Z";
    DATA_EXCEPTION_DUPLICATE_JSON_OBJECT_KEY_VALUE:
      constant SQLSTATE_TYPE := "22030";
    DATA_EXCEPTION_INVALID_ARGUMENT_FOR_SQL_JSON_DATETIME_FUNCTION:
      constant SQLSTATE_TYPE := "22031";
    DATA_EXCEPTION_INVALID_JSON_TEXT:
      constant SQLSTATE_TYPE := "22032";
    DATA_EXCEPTION_INVALID_SQL_JSON_SUBSCRIPT:
      constant SQLSTATE_TYPE := "22033";
    DATA_EXCEPTION_MORE_THAN_ONE_SQL_JSON_ITEM:
      constant SQLSTATE_TYPE := "22034";
    DATA_EXCEPTION_NO_SQL_JSON_ITEM:
      constant SQLSTATE_TYPE := "22035";
    DATA_EXCEPTION_NON_NUMERIC_SQL_JSON_ITEM:
      constant SQLSTATE_TYPE := "22036";
    DATA_EXCEPTION_NON_UNIQUE_KEYS_IN_A_JSON_OBJECT:
      constant SQLSTATE_TYPE := "22037";
    DATA_EXCEPTION_SINGLETON_SQL_JSON_ITEM_REQUIRED:
      constant SQLSTATE_TYPE := "22038";
    DATA_EXCEPTION_SQL_JSON_ARRAY_NOT_FOUND:
      constant SQLSTATE_TYPE := "22039";
    DATA_EXCEPTION_SQL_JSON_MEMBER_NOT_FOUND:
      constant SQLSTATE_TYPE := "2203A";
    DATA_EXCEPTION_SQL_JSON_NUMBER_NOT_FOUND:
      constant SQLSTATE_TYPE := "2203B";
    DATA_EXCEPTION_SQL_JSON_OBJECT_NOT_FOUND:
      constant SQLSTATE_TYPE := "2203C";
    DATA_EXCEPTION_TOO_MANY_JSON_ARRAY_ELEMENTS:
      constant SQLSTATE_TYPE := "2203D";
    DATA_EXCEPTION_TOO_MANY_JSON_OBJECT_MEMBERS:
      constant SQLSTATE_TYPE := "2203E";
    DATA_EXCEPTION_SQL_JSON_SCALAR_REQUIRED:
      constant SQLSTATE_TYPE := "2203F";
    DATA_EXCEPTION_SQL_JSON_ITEM_CANNOT_BE_CAST_TO_TARGET_TYPE:
      constant SQLSTATE_TYPE := "2203G";
    DATA_EXCEPTION_TARGET_IN_JSON_TRANSFORM_ALREADY_EXISTS:
      constant SQLSTATE_TYPE := "22050";
    DATA_EXCEPTION_NULL_IN_REPLACEMENT_VALUE_OF_JSON_TRANSFORM_NOT_ALLOWED:
      constant SQLSTATE_TYPE := "22051";
    DATA_EXCEPTION_TARGET_IN_JSON_TRANSFORM_DOES_NOT_EXIST:
      constant SQLSTATE_TYPE := "22052";
    INTEGRITY_CONSTRAINT_VIOLATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "23000";
    INTEGRITY_CONSTRAINT_VIOLATION_RESTRICT_VIOLATION:
      constant SQLSTATE_TYPE := "23001";
    INVALID_CURSOR_STATE_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "24000";
    INVALID_TRANSACTION_STATE_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "25000";
    INVALID_TRANSACTION_STATE_ACTIVE_SQL_TRANSACTION:
      constant SQLSTATE_TYPE := "25001";
    INVALID_TRANSACTION_STATE_BRANCH_TRANSACTION_ALREADY_ACTIVE:
      constant SQLSTATE_TYPE := "25002";
    INVALID_TRANSACTION_STATE_INAPPROPRIATE_ACCESS_MODE_FOR_BRANCH_TRANSACTION:
      constant SQLSTATE_TYPE := "25003";
    INVALID_TRANSACTION_STATE_INAPPROPRIATE_ISOLATION_LEVEL_FOR_BRANCH_TRANSACTION:
      constant SQLSTATE_TYPE := "25004";
    INVALID_TRANSACTION_STATE_NO_ACTIVE_SQL_TRANSACTION_FOR_BRANCH_TRANSACTION:
      constant SQLSTATE_TYPE := "25005";
    INVALID_TRANSACTION_STATE_READ_ONLY_SQL_TRANSACTION:
      constant SQLSTATE_TYPE := "25006";
    INVALID_TRANSACTION_STATE_SCHEMA_AND_DATA_STATEMENT_MIXING_NOT_SUPPORTED:
      constant SQLSTATE_TYPE := "25007";
    INVALID_TRANSACTION_STATE_HELD_CURSOR_REQUIRES_SAME_ISOLATION_LEVEL:
      constant SQLSTATE_TYPE := "25008";
    INVALID_SQL_STATEMENT_NAME_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "26000";
    TRIGGERED_DATA_CHANGE_VIOLATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "27000";
    TRIGGERED_DATA_CHANGE_VIOLATION_MODIFY_TABLE_MODIFIED_BY_DATA_CHANGE_DELTA_TABLE:
      constant SQLSTATE_TYPE := "27001";
    INVALID_AUTHORIZATION_SPECIFICATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "28000";
    DEPENDENT_PRIVILEGE_DESCRIPTORS_STILL_EXIST_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "2B000";
    INVALID_CHARACTER_SET_NAME_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "2C000";
    INVALID_TRANSACTION_TERMINATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "2D000";
    INVALID_CONNECTION_NAME_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "2E000";
    SQL_ROUTINE_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "2F000";
    SQL_ROUTINE_EXCEPTION_MODIFYING_SQL_DATA_NOT_PERMITTED:
      constant SQLSTATE_TYPE := "2F002";
    SQL_ROUTINE_EXCEPTION_PROHIBITED_SQL_STATEMENT_ATTEMPTED:
      constant SQLSTATE_TYPE := "2F003";
    SQL_ROUTINE_EXCEPTION_READING_SQL_DATA_NOT_PERMITTED:
      constant SQLSTATE_TYPE := "2F004";
    SQL_ROUTINE_EXCEPTION_FUNCTION_EXECUTED_NO_RETURN_STATEMENT:
      constant SQLSTATE_TYPE := "2F005";
    INVALID_COLLATION_NAME_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "2H000";
    INVALID_SQL_STATEMENT_IDENTIFIER_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "30000";
    INVALID_SQL_DESCRIPTOR_NAME_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "33000";
    INVALID_CURSOR_NAME_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "34000";
    INVALID_CONDITION_NUMBER_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "35000";
    CURSOR_SENSITIVITY_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "36000";
    CURSOR_SENSITIVITY_EXCEPTION_REQUEST_REJECTED:
      constant SQLSTATE_TYPE := "36001";
    CURSOR_SENSITIVITY_EXCEPTION_REQUEST_FAILED:
      constant SQLSTATE_TYPE := "36002";
    EXTERNAL_ROUTINE_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "38000";
    EXTERNAL_ROUTINE_EXCEPTION_CONTAINING_SQL_NOT_PERMITTED:
      constant SQLSTATE_TYPE := "38001";
    EXTERNAL_ROUTINE_EXCEPTION_MODIFYING_SQL_DATA_NOT_PERMITTED:
      constant SQLSTATE_TYPE := "38002";
    EXTERNAL_ROUTINE_EXCEPTION_PROHIBITED_SQL_STATEMENT_ATTEMPTED:
      constant SQLSTATE_TYPE := "38003";
    EXTERNAL_ROUTINE_EXCEPTION_READING_SQL_DATA_NOT_PERMITTED:
      constant SQLSTATE_TYPE := "38004";
    EXTERNAL_ROUTINE_INVOCATION_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "39000";
    EXTERNAL_ROUTINE_INVOCATION_EXCEPTION_NULL_VALUE_NOT_ALLOWED:
      constant SQLSTATE_TYPE := "39004";
    SAVEPOINT_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "3B000";
    SAVEPOINT_EXCEPTION_INVALID_SPECIFICATION:
      constant SQLSTATE_TYPE := "3B001";
    SAVEPOINT_EXCEPTION_TOO_MANY:
      constant SQLSTATE_TYPE := "3B002";
    AMBIGUOUS_CURSOR_NAME_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "3C000";
    INVALID_CATALOG_NAME_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "3D000";
    INVALID_SCHEMA_NAME_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "3F000";
    TRANSACTION_ROLLBACK_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "40000";
    TRANSACTION_ROLLBACK_SERIALIZATION_FAILURE:
      constant SQLSTATE_TYPE := "40001";
    TRANSACTION_ROLLBACK_INTEGRITY_CONSTRAINT_VIOLATION:
      constant SQLSTATE_TYPE := "40002";
    TRANSACTION_ROLLBACK_STATEMENT_COMPLETION_UNKNOWN:
      constant SQLSTATE_TYPE := "40003";
    TRANSACTION_ROLLBACK_TRIGGERED_ACTION_EXCEPTION:
      constant SQLSTATE_TYPE := "40004";
    SYNTAX_ERROR_OR_ACCESS_RULE_VIOLATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "42000";
    WITH_CHECK_OPTION_VIOLATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "44000";
