
-- The following lines of Ada code are intended to be inserted into the Ada package
-- Interfaces.SQL that is defined in ISO/IEC 9075-2. 

-- They should be inserted immediately following the line that reads:
--   package SQLSTATE_CODES is

    WARNING_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "01000";
    WARNING_COLUMN_CANNOT_BE_MAPPED_TO_XML:
      constant SQLSTATE_TYPE := "01010";
    SQL_XML_MAPPING_ERROR_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0N000";
    SQL_XML_MAPPING_ERROR_UNMAPPABLE_XML_NAME:
      constant SQLSTATE_TYPE := "0N001";
    SQL_XML_MAPPING_ERROR_INVALID_XML_CHARACTER:
      constant SQLSTATE_TYPE := "0N002";
    XQUERY_ERROR_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "10000";
    DATA_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "22000";
    DATA_EXCEPTION_NOT_AN_XML_DOCUMENT:
      constant SQLSTATE_TYPE := "2200L";
    DATA_EXCEPTION_INVALID_XML_DOCUMENT:
      constant SQLSTATE_TYPE := "2200M";
    DATA_EXCEPTION_INVALID_XML_CONTENT:
      constant SQLSTATE_TYPE := "2200N";
    DATA_EXCEPTION_XML_VALUE_OVERFLOW:
      constant SQLSTATE_TYPE := "2200R";
    DATA_EXCEPTION_INVALID_COMMENT:
      constant SQLSTATE_TYPE := "2200S";
    DATA_EXCEPTION_INVALID_PROCESSING_INSTRUCTION:
      constant SQLSTATE_TYPE := "2200T";
    DATA_EXCEPTION_NOT_AN_XQUERY_DOCUMENT_NODE:
      constant SQLSTATE_TYPE := "2200U";
    DATA_EXCEPTION_INVALID_XQUERY_CONTEXT_ITEM:
      constant SQLSTATE_TYPE := "2200V";
    DATA_EXCEPTION_XQUERY_SERIALIZATION_ERROR:
      constant SQLSTATE_TYPE := "2200W";
    DATA_EXCEPTION_XQUERY_SEQUENCE_CANNOT_BE_VALIDATED:
      constant SQLSTATE_TYPE := "2201J";
    DATA_EXCEPTION_XQUERY_DOCUMENT_NODE_CANNOT_BE_VALIDATED:
      constant SQLSTATE_TYPE := "2201K";
    DATA_EXCEPTION_NO_XML_SCHEMA_FOUND:
      constant SQLSTATE_TYPE := "2201L";
    DATA_EXCEPTION_ELEMENT_NAMESPACE_NOT_DECLARED:
      constant SQLSTATE_TYPE := "2201M";
    DATA_EXCEPTION_GLOBAL_ELEMENT_NOT_DECLARED:
      constant SQLSTATE_TYPE := "2201N";
    DATA_EXCEPTION_NO_XML_ELEMENT_WITH_THE_SPECIFIED_QNAME:
      constant SQLSTATE_TYPE := "2201P";
    DATA_EXCEPTION_NO_XML_ELEMENT_WITH_THE_SPECIFIED_NAMESPACE:
      constant SQLSTATE_TYPE := "2201Q";
    DATA_EXCEPTION_VALIDATION_FAILURE:
      constant SQLSTATE_TYPE := "2201R";
