
-- The following lines of Ada code are intended to be inserted into the Ada package
-- Interfaces.SQL that is defined in ISO/IEC 9075-2. 

-- They should be inserted immediately following the line that reads:
--   package SQLSTATE_CODES is

    INVALID_FOREIGN_SERVER_SPECIFICATION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0X000";
    PASS_THROUGH_SPECIFIC_CONDITION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "0Y000";
    PASS_THROUGH_SPECIFIC_CONDITION_INVALID_CURSOR_OPTION:
      constant SQLSTATE_TYPE := "0Y001";
    PASS_THROUGH_SPECIFIC_CONDITION_INVALID_CURSOR_ALLOCATION:
      constant SQLSTATE_TYPE := "0Y002";
    DATA_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "22000";
    DATA_EXCEPTION_INVALID_DATA_SPECIFIED_FOR_DATALINK:
      constant SQLSTATE_TYPE := "22017";
    DATA_EXCEPTION_NULL_ARGUMENT_PASSED_TO_DATALINK_CONSTRUCTOR:
      constant SQLSTATE_TYPE := "2201A";
    DATA_EXCEPTION_DATALINK_VALUE_EXCEEDS_MAXIMUM_LENGTH:
      constant SQLSTATE_TYPE := "2201D";
    FDW_SPECIFIC_CONDITION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "HV000";
    FDW_SPECIFIC_CONDITION_MEMORY_ALLOCATION_ERROR:
      constant SQLSTATE_TYPE := "HV001";
    FDW_SPECIFIC_CONDITION_INVALID_DATA_TYPE:
      constant SQLSTATE_TYPE := "HV004";
    FDW_SPECIFIC_CONDITION_COLUMN_NAME_NOT_FOUND:
      constant SQLSTATE_TYPE := "HV005";
    FDW_SPECIFIC_CONDITION_INVALID_DATA_TYPE_DESCRIPTORS:
      constant SQLSTATE_TYPE := "HV006";
    FDW_SPECIFIC_CONDITION_INVALID_COLUMN_NAME:
      constant SQLSTATE_TYPE := "HV007";
    FDW_SPECIFIC_CONDITION_INVALID_USE_OF_NULL_POINTER:
      constant SQLSTATE_TYPE := "HV009";
    FDW_SPECIFIC_CONDITION_INVALID_STRING_FORMAT:
      constant SQLSTATE_TYPE := "HV00A";
    FDW_SPECIFIC_CONDITION_INVALID_HANDLE:
      constant SQLSTATE_TYPE := "HV00B";
    FDW_SPECIFIC_CONDITION_INVALID_OPTION_INDEX:
      constant SQLSTATE_TYPE := "HV00C";
    FDW_SPECIFIC_CONDITION_INVALID_OPTION_NAME:
      constant SQLSTATE_TYPE := "HV00D";
    FDW_SPECIFIC_CONDITION_OPTION_NAME_NOT_FOUND:
      constant SQLSTATE_TYPE := "HV00J";
    FDW_SPECIFIC_CONDITION_UNABLE_TO_CREATE_EXECUTION:
      constant SQLSTATE_TYPE := "HV00L";
    FDW_SPECIFIC_CONDITION_UNABLE_TO_CREATE_REPLY:
      constant SQLSTATE_TYPE := "HV00M";
    FDW_SPECIFIC_CONDITION_UNABLE_TO_ESTABLISH_CONNECTION:
      constant SQLSTATE_TYPE := "HV00N";
    FDW_SPECIFIC_CONDITION_NO_SCHEMAS:
      constant SQLSTATE_TYPE := "HV00P";
    FDW_SPECIFIC_CONDITION_SCHEMA_NOT_FOUND:
      constant SQLSTATE_TYPE := "HV00Q";
    FDW_SPECIFIC_CONDITION_TABLE_NOT_FOUND:
      constant SQLSTATE_TYPE := "HV00R";
    FDW_SPECIFIC_CONDITION_FUNCTION_SEQUENCE_ERROR:
      constant SQLSTATE_TYPE := "HV010";
    FDW_SPECIFIC_CONDITION_LIMIT_ON_NUMBER_OF_HANDLES_EXCEEDED:
      constant SQLSTATE_TYPE := "HV014";
    FDW_SPECIFIC_CONDITION_INCONSISTENT_DESCRIPTOR_INFORMATION:
      constant SQLSTATE_TYPE := "HV021";
    FDW_SPECIFIC_CONDITION_INVALID_ATTRIBUTE_VALUE:
      constant SQLSTATE_TYPE := "HV024";
    FDW_SPECIFIC_CONDITION_INVALID_STRING_LENGTH_OR_BUFFER_LENGTH:
      constant SQLSTATE_TYPE := "HV090";
    FDW_SPECIFIC_CONDITION_INVALID_DESCRIPTOR_FIELD_IDENTIFIER:
      constant SQLSTATE_TYPE := "HV091";
    DATALINK_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "HW000";
    DATALINK_EXCEPTION_EXTERNAL_FILE_NOT_LINKED:
      constant SQLSTATE_TYPE := "HW001";
    DATALINK_EXCEPTION_EXTERNAL_FILE_ALREADY_LINKED:
      constant SQLSTATE_TYPE := "HW002";
    DATALINK_EXCEPTION_REFERENCED_FILE_DOES_NOT_EXIST:
      constant SQLSTATE_TYPE := "HW003";
    DATALINK_EXCEPTION_INVALID_WRITE_TOKEN:
      constant SQLSTATE_TYPE := "HW004";
    DATALINK_EXCEPTION_INVALID_DATALINK_CONSTRUCTION:
      constant SQLSTATE_TYPE := "HW005";
    DATALINK_EXCEPTION_INVALID_WRITE_PERMISSION_FOR_UPDATE:
      constant SQLSTATE_TYPE := "HW006";
    DATALINK_EXCEPTION_REFERENCED_FILE_NOT_VALID:
      constant SQLSTATE_TYPE := "HW007";
    CLI_SPECIFIC_CONDITION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "HY000";
    CLI_SPECIFIC_CONDITION_INVALID_ATTRIBUTE_IDENTIFIER:
      constant SQLSTATE_TYPE := "HY092";
    CLI_SPECIFIC_CONDITION_INVALID_DATALINK_VALUE:
      constant SQLSTATE_TYPE := "HY093";
