
-- The following lines of Ada code are intended to be inserted into the Ada package
-- Interfaces.SQL that is defined in ISO/IEC 9075-2. 

-- They should be inserted immediately following the line that reads:
--   package SQLSTATE_CODES is

    DATA_EXCEPTION_NO_SUBCLASS:
      constant SQLSTATE_TYPE := "22000";
    DATA_EXCEPTION_MD_ARRAY_NULL_LIMIT_IN_SUBSET:
      constant SQLSTATE_TYPE := "2203J";
    DATA_EXCEPTION_MD_ARRAY_NULL_LIMIT_IN_MD_EXTENT:
      constant SQLSTATE_TYPE := "2203K";
    DATA_EXCEPTION_MD_ARRAY_SUBSET_NOT_WITHIN_MD_EXTENT:
      constant SQLSTATE_TYPE := "2203L";
    DATA_EXCEPTION_MD_ARRAY_DUPLICATE_COORDINATE_IN_QUERY_CONSTRUCTOR:
      constant SQLSTATE_TYPE := "2203M";
    DATA_EXCEPTION_MD_ARRAY_NULL_COORDINATE_IN_QUERY_CONSTRUCTOR:
      constant SQLSTATE_TYPE := "2203N";
    DATA_EXCEPTION_MD_ARRAY_COORDINATE_NOT_WITHIN_SPECIFIED_MD_EXTENT:
      constant SQLSTATE_TYPE := "2203P";
    DATA_EXCEPTION_MD_ARRAY_SOURCE_MD_EXTENT_NOT_STRICTLY_WITHIN_MAXIMUM_TARGET_MD_EXTENT:
      constant SQLSTATE_TYPE := "2203Q";
    DATA_EXCEPTION_MD_ARRAY_OPERANDS_WITH_NON_MATCHING_MD_EXTENTS:
      constant SQLSTATE_TYPE := "2203R";
    DATA_EXCEPTION_MD_ARRAY_INVALID_MD_AXIS:
      constant SQLSTATE_TYPE := "2203T";
    DATA_EXCEPTION_MD_ARRAY_LOWER_LIMIT_GREATER_THAN_UPPER_LIMIT:
      constant SQLSTATE_TYPE := "2203U";
    DATA_EXCEPTION_MD_ARRAY_ELEMENT_ERROR:
      constant SQLSTATE_TYPE := "2203X";
    DATA_EXCEPTION_MD_ARRAY_DECODING_ERROR:
      constant SQLSTATE_TYPE := "2203Y";
    DATA_EXCEPTION_MD_ARRAY_ENCODING_ERROR:
      constant SQLSTATE_TYPE := "2203Z";
    DATA_EXCEPTION_MD_ARRAY_ELEMENT_REFERENCE_NOT_WITHIN_MD_EXTENT:
      constant SQLSTATE_TYPE := "22040";
    DATA_EXCEPTION_MD_ARRAY_NULL_VALUE_IN_MD_ARRAY_TARGET:
      constant SQLSTATE_TYPE := "22041";
    DATA_EXCEPTION_MD_ARRAY_SOURCE_MD_EXTENT_NOT_STRICTLY_WITHIN_TARGET_MD_EXTENT:
      constant SQLSTATE_TYPE := "22042";
    DATA_EXCEPTION_MD_ARRAY_TARGET_MD_EXTENT_NOT_STRICTLY_WITHIN_MAXIMUM_MD_EXTENT:
      constant SQLSTATE_TYPE := "22043";
    DATA_EXCEPTION_MD_ARRAY_LIMIT_IN_MD_EXTENT_OUT_OF_BOUNDS:
      constant SQLSTATE_TYPE := "22044";
