
/*
The following material is a "digital artifact" containing a series of complete
or partial SQL "schema definition" and/or "schema manipulation" statements
that effectively create or modify an SQL schema to support the facilities defined in one
part of ISO/IEC 9075. 

These statements may be used by SQL-implementations to create their initial
Information and Definition schemata. 
*/

      
      
/* Definition Schema */
      
INSERT INTO DATA_TYPES_LIST ( DATA_TYPE )
    VALUES ('DATALINK');

  
INSERT INTO TABLE_TYPES_LIST ( TABLE_TYPE )
    VALUES ('FOREIGN');

  
INSERT INTO USAGE_OBJECT_TYPES_LIST ( OBJECT_TYPE )
    VALUES ('FOREIGN DATA WRAPPER'),
           ('FOREIGN SERVER');

  
CREATE TABLE COLUMN_OPTIONS (
    TABLE_CATALOG                                INFORMATION_SCHEMA.SQL_IDENTIFIER,
    TABLE_SCHEMA                                 INFORMATION_SCHEMA.SQL_IDENTIFIER,
    TABLE_NAME                                   INFORMATION_SCHEMA.SQL_IDENTIFIER,
    COLUMN_NAME                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_NAME                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_VALUE                                 INFORMATION_SCHEMA.CHARACTER_DATA,

    CONSTRAINT COLUMN_OPTIONS_PRIMARY_KEY
      PRIMARY KEY ( TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME,
                    COLUMN_NAME, OPTION_NAME ),

    CONSTRAINT COLUMN_OPTIONS_FOREIGN_KEY_COLUMNS
      FOREIGN KEY ( TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME )
        REFERENCES COLUMNS
    );

  
ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN DATALINK_LINK_CONTROL                    INFORMATION_SCHEMA.YES_OR_NO;

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN DATALINK_INTEGRITY                       INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT DATA_TYPE_DESCRIPTOR_DATALINK_INTEGRITY
        CHECK ( DATALINK_INTEGRITY IN ('ALL', 'SELECTIVE', 'NONE') );

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN DATALINK_READ_PERMISSION                 INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT DATA_TYPE_DESCRIPTOR_DATALINK_READ_PERMISSION
        CHECK ( DATALINK_READ_PERMISSION IN ('FS', 'DB') );

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN DATALINK_WRITE_PERMISSION                INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT DATA_TYPE_DESCRIPTOR_DATALINK_WRITE_PERMISSION
        CHECK ( DATALINK_WRITE_PERMISSION IN
                ( 'FS', 'BLOCKED',
                  'ADMIN REQUIRING TOKEN FOR UPDATE',
                  'ADMIN NOT REQUIRING TOKEN FOR UPDATE' ) );

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN DATALINK_RECOVERY                        INFORMATION_SCHEMA.YES_OR_NO;

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD COLUMN DATALINK_UNLINK                          INFORMATION_SCHEMA.CHARACTER_DATA
      CONSTRAINT DATA_TYPE_DESCRIPTOR_DATALINK_UNLINK
        CHECK ( DATALINK_UNLINK IN
                ( 'DELETE', 'RESTORE', 'NONE' ) );

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD CONSTRAINT DATA_TYPE_DESCRIPTOR_DATALINK_VALID_COMBINATIONS
      CHECK ( DATALINK_LINK_CONTROL = 'NO'
         OR
            ( ( DATALINK_INTEGRITY <> 'SELECTIVE'
             OR
                ( DATALINK_READ_PERMISSION = 'FS'
              AND
                  DATALINK_WRITE_PERMISSION = 'FS'
              AND
                  DATALINK_RECOVERY = 'NO' ) )
          AND
              ( DATALINK_READ_PERMISSION <> 'DB'
             OR
                DATALINK_WRITE_PERMISSION <> 'FS' )
          AND
              ( DATALINK_WRITE_PERMISSION = 'FS'
             OR
                ( DATALINK_INTEGRITY = 'ALL'
              AND
                  DATALINK_UNLINK <> 'NONE' ) )
          AND
              ( DATALINK_WRITE_PERMISSION <> 'FS'
             OR
                ( DATALINK_READ_PERMISSION = 'FS'
              AND
                  DATALINK_RECOVERY = 'NO'
              AND
                  DATALINK_UNLINK = 'NONE' ) )
          AND
              ( DATALINK_RECOVERY <> 'YES'
             OR
                DATALINK_WRITE_PERMISSION <> 'FS' )
          AND
              ( DATALINK_UNLINK <> 'DELETE'
             OR
                DATALINK_READ_PERMISSION = 'DB' ) ) );

ALTER TABLE DATA_TYPE_DESCRIPTOR
    ADD CONSTRAINT DATA_TYPE_DESCRIPTOR_DATA_TYPE_CHECK_NOT_DATALINK
      CHECK ( ( DATA_TYPE <> 'DATALINK' 
        AND ( DATALINK_LINK_CONTROL, DATALINK_INTEGRITY, DATALINK_READ_PERMISSION,
              DATALINK_WRITE_PERMISSION, DATALINK_RECOVERY, DATALINK_UNLINK ) IS NULL )
       OR
            ( DATA_TYPE = 'DATALINK' 
        AND ( DATALINK_LINK_CONTROL, DATALINK_INTEGRITY, DATALINK_READ_PERMISSION,
              DATALINK_WRITE_PERMISSION, DATALINK_RECOVERY, DATALINK_UNLINK ) IS NOT NULL ) );

  
CREATE TABLE FOREIGN_DATA_WRAPPER_OPTIONS (
    FOREIGN_DATA_WRAPPER_CATALOG                 INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_DATA_WRAPPER_NAME                    INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_NAME                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_VALUE                                 INFORMATION_SCHEMA.SQL_CHARACTER_DATA,

    CONSTRAINT FOREIGN_DATA_WRAPPER_OPTIONS_PRIMARY_KEY
      PRIMARY KEY ( FOREIGN_DATA_WRAPPER_CATALOG, FOREIGN_DATA_WRAPPER_NAME,
                    OPTION_NAME ),

    CONSTRAINT FOREIGN_DATA_WRAPPER_OPTIONS_FOREIGN_KEY_FOREIGN_DATA_WRAPPERS
      FOREIGN KEY ( FOREIGN_DATA_WRAPPER_CATALOG, FOREIGN_DATA_WRAPPER_NAME )
        REFERENCES FOREIGN_DATA_WRAPPERS
    );

  
CREATE TABLE FOREIGN_DATA_WRAPPERS (
    FOREIGN_DATA_WRAPPER_CATALOG                 INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_DATA_WRAPPER_NAME                    INFORMATION_SCHEMA.SQL_IDENTIFIER,
    AUTHORIZATION_IDENTIFIER                     INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT FOREIGN_DATA_WRAPPER_AUTHORIZATION_IDENTIFIER_NOT_NULL NOT NULL,
    LIBRARY_NAME                                 INFORMATION_SCHEMA.SQL_CHARACTER_DATA
      CONSTRAINT FOREIGN_DATA_WRAPPER_LIBRARY_NAME_NOT_NULL NOT NULL,
    FOREIGN_DATA_WRAPPER_LANGUAGE                INFORMATION_SCHEMA.SQL_CHARACTER_DATA
      CONSTRAINT FOREIGN_DATA_WRAPPER_LANGUAGE_NOT_NULL NOT NULL,

    CONSTRAINT FOREIGN_DATA_WRAPPERS_PRIMARY_KEY
      PRIMARY KEY ( FOREIGN_DATA_WRAPPER_CATALOG, FOREIGN_DATA_WRAPPER_NAME ),

    CONSTRAINT FOREIGN_DATA_WRAPPERS_LANGUAGE_CHECK
      CHECK ( FOREIGN_DATA_WRAPPER_LANGUAGE IN
        ( 'ADA', 'C', 'COBOL', 'FORTRAN',
          'MUMPS', 'PASCAL', 'PLI' ) ),

    CONSTRAINT FOREIGN_DATA_WRAPPERS_FOREIGN_KEY_AUTHORIZATIONS
      FOREIGN KEY ( AUTHORIZATION_IDENTIFIER )
        REFERENCES AUTHORIZATIONS,

    CONSTRAINT FOREIGN_DATA_WRAPPERS_FOREIGN_KEY_CATALOG_NAMES
      FOREIGN KEY ( CATALOG_NAME )
        REFERENCES CATALOG_NAMES
    );

  
CREATE TABLE FOREIGN_SERVER_OPTIONS (
    FOREIGN_SERVER_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_SERVER_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_NAME                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_VALUE                                 INFORMATION_SCHEMA.SQL_CHARACTER_DATA,

    CONSTRAINT FOREIGN_SERVERS_PRIMARY_KEY
      PRIMARY KEY ( FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME, OPTION_NAME ),

    CONSTRAINT FOREIGN_SERVER_OPTIONS_FOREIGN_KEY_FOREIGN_SERVERS
      FOREIGN KEY ( FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME )
        REFERENCES FOREIGN_SERVERS
    );

  
CREATE TABLE FOREIGN_SERVERS (
    FOREIGN_SERVER_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_SERVER_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_DATA_WRAPPER_CATALOG                 INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT FOREIGN_SERVER_FOREIGN_DATA_WRAPPER_CATALOG_NOT_NULL NOT NULL,
    FOREIGN_DATA_WRAPPER_NAME                    INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT FOREIGN_SERVER_FOREIGN_DATA_WRAPPER_NAME_NOT_NULL NOT NULL,
    FOREIGN_SERVER_TYPE                          INFORMATION_SCHEMA.CHARACTER_DATA,
    FOREIGN_SERVER_VERSION                       INFORMATION_SCHEMA.CHARACTER_DATA,
    AUTHORIZATION_IDENTIFIER                     INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT AUTHORIZATION_IDENTIFIER_NOT_NULL NOT NULL,

    CONSTRAINT FOREIGN_SERVERS_PRIMARY_KEY
      PRIMARY KEY ( FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME ),

    CONSTRAINT FOREIGN_SERVERS_FOREIGN_KEY_FOREIGN_DATA_WRAPPERS
      FOREIGN KEY ( FOREIGN_DATA_WRAPPER_CATALOG, FOREIGN_DATA_WRAPPER_NAME )
        REFERENCES FOREIGN_DATA_WRAPPERS,

    CONSTRAINT FOREIGN_SERVERS_FOREIGN_KEY_AUTHORIZATIONS
      FOREIGN KEY ( AUTHORIZATION_IDENTIFIER )
        REFERENCES AUTHORIZATIONS,

    CONSTRAINT FOREIGN_SERVERS_FOREIGN_KEY_CATALOG_NAMES
      FOREIGN KEY ( CATALOG_NAME )
        REFERENCES CATALOG_NAMES
    );

  
CREATE TABLE FOREIGN_TABLE_OPTIONS (
    FOREIGN_TABLE_CATALOG                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_TABLE_SCHEMA                         INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_TABLE_NAME                           INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_NAME                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_VALUE                                 INFORMATION_SCHEMA.SQL_CHARACTER_DATA,

    CONSTRAINT FOREIGN_TABLE_OPTIONS_PRIMARY_KEY
      PRIMARY KEY ( FOREIGN_TABLE_CATALOG, FOREIGN_TABLE_SCHEMA,
                   FOREIGN_TABLE_NAME, OPTION_NAME ),

    CONSTRAINT FOREIGN_TABLE_OPTIONS_FOREIGN_KEY_FOREIGN_TABLES
      FOREIGN KEY (FOREIGN_TABLE_CATALOG, FOREIGN_TABLE_SCHEMA, FOREIGN_TABLE_NAME )
        REFERENCES FOREIGN_TABLES
    );

  
CREATE TABLE FOREIGN_TABLES (
    FOREIGN_TABLE_CATALOG                        INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_TABLE_SCHEMA                         INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_TABLE_NAME                           INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_SERVER_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER
     CONSTRAINT FOREIGN_SERVER_CATALOG_NOT_NULL NOT NULL,
    FOREIGN_SERVER_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER
     CONSTRAINT FOREIGN_SERVER_NAME_NOT_NULL NOT NULL,

    CONSTRAINT FOREIGN_TABLES_PRIMARY_KEY
      PRIMARY KEY ( FOREIGN_TABLE_CATALOG, FOREIGN_TABLE_SCHEMA,
                    FOREIGN_TABLE_NAME ),

    CONSTRAINT FOREIGN_TABLES_FOREIGN_KEY_FOREIGN_SERVERS
      FOREIGN KEY ( FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME )
        REFERENCES FOREIGN_SERVERS,

    CONSTRAINT FOREIGN_TABLES_IN_TABLES_CHECK
      CHECK ( ( FOREIGN_TABLE_CATALOG, FOREIGN_TABLE_SCHEMA,
                FOREIGN_TABLE_NAME )
           IN
              ( SELECT TABLE_CATALOG, TABLE_SCHEMA,
                       TABLE_NAME
                FROM TABLES
                WHERE TABLE_TYPE = 'FOREIGN' ) )
    );

  
CREATE TABLE ROUTINE_MAPPING_OPTIONS (
    ROUTINE_MAPPING_NAME                         INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_NAME                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_VALUE                                 INFORMATION_SCHEMA.SQL_CHARACTER_DATA,

    CONSTRAINT ROUTINE_MAPPING_OPTIONS_PRIMARY_KEY
      PRIMARY KEY ( ROUTINE_MAPPING_NAME, OPTION_NAME ),

    CONSTRAINT ROUTINE_MAPPING_OPTIONS_FOREIGN_KEY_ROUTINE_MAPPINGS
      FOREIGN KEY ( ROUTINE_MAPPING_NAME )
        REFERENCES ROUTINE_MAPPINGS
    );

  
CREATE TABLE ROUTINE_MAPPINGS (
    ROUTINE_MAPPING_NAME                         INFORMATION_SCHEMA.SQL_IDENTIFIER,
    SPECIFIC_CATALOG                             INFORMATION_SCHEMA.SQL_IDENTIFIER
     CONSTRAINT SPECIFIC_CATALOG_NOT_NULL NOT NULL,
    SPECIFIC_SCHEMA                              INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT SPECIFIC_SCHEMA_NOT_NULL NOT NULL,
    SPECIFIC_NAME                       INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT SPECIFIC_NAME_NOT_NULL NOT NULL,
    FOREIGN_SERVER_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT FOREIGN_SERVER_CATALOG_NOT_NULL NOT NULL,
    FOREIGN_SERVER_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER
      CONSTRAINT FOREIGN_SERVER_NAME_NOT_NULL NOT NULL,

    CONSTRAINT ROUTINE_MAPPINGS_PRIMARY_KEY
      PRIMARY KEY ( ROUTINE_MAPPING_NAME ),

    CONSTRAINT ROUTINE_MAPPINGS_FOREIGN_KEY_FOREIGN_SERVERS
      FOREIGN KEY ( FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME )
        REFERENCES FOREIGN_SERVERS,

    CONSTRAINT ROUTINE_MAPPINGS_FOREIGN_KEY_ROUTINES
      FOREIGN KEY ( SPECIFIC_CATALOG, SPECIFIC_SCHEMA, SPECIFIC_NAME )
        REFERENCES ROUTINES,

    CONSTRAINT ROUTINE_MAPPINGS_UNIQUE_MAPPING_ROUTINE_SERVER
      UNIQUE ( SPECIFIC_CATALOG, SPECIFIC_SCHEMA,
               SPECIFIC_NAME, FOREIGN_SERVER_CATALOG,
               FOREIGN_SERVER_NAME )
    );

  
    ALTER TABLE TABLES
      ADD CONSTRAINT TABLES_CHECK_NOT_FOREIGN       
        CHECK ( NOT EXISTS
                ( SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
                  FROM TABLES
                  WHERE TABLE_TYPE = 'FOREIGN'
                  EXCEPT
                  SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
                  FROM FOREIGN_TABLES ) )

  
ALTER TABLE USAGE_PRIVILEGES
   ADD CONSTRAINT USAGE_PRIVILEGES_CHECK_REFERENCES_FOREIGN_DATA_WRAPPER
       CHECK ( OBJECT_TYPE <> 'FOREIGN DATA WRAPPER'
              OR
             ( OBJECT_CATALOG, OBJECT_NAME) IN
             ( SELECT FOREIGN_DATA_WRAPPER_CATALOG, FOREIGN_DATA_WRAPPER
               FROM FOREIGN_DATA_WRAPPERS ) );

ALTER TABLE USAGE_PRIVILEGES
   ADD CONSTRAINT USAGE_PRIVILEGES_CHECK_REFERENCES_FOREIGN_SERVER
       CHECK ( OBJECT_TYPE <> 'FOREIGN SERVER'
              OR
             ( OBJECT_CATALOG, OBJECT_NAME) IN
             ( SELECT FOREIGN_SERVER_CATALOG, FOREIGN_SERVER
               FROM FOREIGN_SERVERS ) );

  
CREATE TABLE USER_MAPPING_OPTIONS (
    AUTHORIZATION_IDENTIFIER                     INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_SERVER_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_SERVER_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_NAME                                  INFORMATION_SCHEMA.SQL_IDENTIFIER,
    OPTION_VALUE                                 INFORMATION_SCHEMA.SQL_CHARACTER_DATA,

    CONSTRAINT USER_MAPPING_OPTIONS_PRIMARY_KEY
      PRIMARY KEY ( AUTHORIZATION_IDENTIFIER, FOREIGN_SERVER_CATALOG,
                    FOREIGN_SERVER_NAME, OPTION_NAME ),

    CONSTRAINT USER_MAPPING_OPTIONS_FOREIGN_KEY_USER_MAPPINGS
      FOREIGN KEY ( AUTHORIZATION_IDENTIFIER, FOREIGN_SERVER_CATALOG,
                    FOREIGN_SERVER_NAME )
        REFERENCES USER_MAPPINGS
    );

  
CREATE TABLE USER_MAPPINGS (
    AUTHORIZATION_IDENTIFIER                     INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_SERVER_CATALOG                       INFORMATION_SCHEMA.SQL_IDENTIFIER,
    FOREIGN_SERVER_NAME                          INFORMATION_SCHEMA.SQL_IDENTIFIER,

    CONSTRAINT USER_MAPPINGS_PRIMARY_KEY
      PRIMARY KEY ( AUTHORIZATION_IDENTIFIER, FOREIGN_SERVER_CATALOG,
                    FOREIGN_SERVER_NAME ),

    CONSTRAINT USER_MAPPINGS_FOREIGN_KEY_FOREIGN_SERVERS
      FOREIGN KEY ( FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME )
        REFERENCES FOREIGN_SERVERS,

    CONSTRAINT USER_MAPPINGS_FOREIGN_KEY_AUTHORIZATIONS
      FOREIGN KEY ( AUTHORIZATION_IDENTIFIER )
        REFERENCES AUTHORIZATIONS
    );

  
      
      
/* Information Schema */      
      
/* Modify the ATTRIBUTES view by inserting after the text:
     
        MAXIMUM_CARDINALITY, A.DTD_IDENTIFIER, IS_DERIVED_REFERENCE_ATTRIBUTE,
        DECLARED_DATA_TYPE, DECLARED_NUMERIC_PRECISION,
        DECLARED_NUMERIC_SCALE

   the text:
     
      , D1.DATALINK_LINK_CONTROL, D1.DATALINK_INTEGRITY, D1.DATALINK_READ_PERMISSION,
      D1.DATALINK_WRITE_PERMISSION, D1.DATALINK_RECOVERY, D1.DATALINK_UNLINK

*/
    
  
CREATE VIEW COLUMN_OPTIONS AS
    SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME,
           COLUMN_NAME, OPTION_NAME, OPTION_VALUE
    FROM DEFINITION_SCHEMA.COLUMN_OPTIONS CO
    WHERE ( CO.TABLE_CATALOG, CO.TABLE_SCHEMA, CO.TABLE_NAME, CO.COLUMN_NAME )
       IN ( SELECT CP.TABLE_CATALOG, CP.TABLE_SCHEMA, CP.TABLE_NAME,
                   CP.COLUMN_NAME
            FROM DEFINITION_SCHEMA.COLUMN_PRIVILEGES AS CP
            WHERE ( CP.GRANTEE IN
                    ( 'PUBLIC', CURRENT_USER )
                 OR
                    CP.GRANTEE IN
                    ( SELECT ROLE_NAME
                      FROM ENABLED_ROLES ) ) )
              AND
                  CO.TABLE_CATALOG
                = ( SELECT CATALOG_NAME
                    FROM INFORMATION_SCHEMA_CATALOG_NAME ) ;

GRANT SELECT ON TABLE COLUMN_OPTIONS
    TO PUBLIC WITH GRANT OPTION;

  
/* Modify the COLUMNS view by inserting after the text:
     
      COALESCE (D1.DECLARED_DATA_TYPE, D2.DECLARED_DATA_TYPE)
               AS DECLARED_DATA_TYPE,
      COALESCE (D1.DECLARED_NUMERIC_PRECISION, D2.DECLARED_NUMERIC_PRECISION)
               AS DECLARED_NUMERIC_PRECISION,
      COALESCE (D1.DECLARED_NUMERIC_SCALE, D2.DECLARED_NUMERIC_SCALE)
               AS DECLARED_NUMERIC_SCALE

   the text:
     
      , DATALINK_LINK_CONTROL, DATALINK_INTEGRITY, DATALINK_READ_PERMISSION,
      DATALINK_WRITE_PERMISSION, DATALINK_RECOVERY, DATALINK_UNLINK

*/
    
  
CREATE VIEW FOREIGN_DATA_WRAPPER_OPTIONS AS
    SELECT FOREIGN_DATA_WRAPPER_CATALOG, FOREIGN_DATA_WRAPPER_NAME,
           OPTION_NAME, OPTION_VALUE
    FROM DEFINITION_SCHEMA.FOREIGN_DATA_WRAPPER_OPTIONS
    WHERE ( FOREIGN_DATA_WRAPPER_CATALOG, FOREIGN_DATA_WRAPPER_NAME )
       IN ( SELECT FOREIGN_DATA_WRAPPER_CATALOG, FOREIGN_DATA_WRAPPER_NAME
            FROM INFORMATION_SCHEMA.FOREIGN_DATA_WRAPPERS ) ;

GRANT SELECT ON TABLE FOREIGN_DATA_WRAPPER_OPTIONS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW FOREIGN_DATA_WRAPPERS AS
    SELECT FOREIGN_DATA_WRAPPER_CATALOG, FOREIGN_DATA_WRAPPER_NAME,
           AUTHORIZATION_IDENTIFIER, LIBRARY_NAME, FOREIGN_DATA_WRAPPER_LANGUAGE
    FROM DEFINITION_SCHEMA.FOREIGN_DATA_WRAPPERS W
    WHERE ( W.FOREIGN_DATA_WRAPPER_CATALOG, '', W.FOREIGN_DATA_WRAPPER_NAME )
       IN ( SELECT UP.OBJECT_CATALOG, UP.OBJECT_SCHEMA, UP.OBJECT_NAME
            FROM DEFINITION_SCHEMA.USAGE_PRIVILEGES AS UP
            WHERE ( UP.GRANTEE IN
                    ( 'PUBLIC', CURRENT_USER )
                 OR
                    UP.GRANTEE IN
                    ( SELECT ROLE_NAME
                      FROM ENABLED_ROLES ) ) )
      AND
          W.FOREIGN_DATA_WRAPPER_CATALOG
        = ( SELECT CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME ) ;

GRANT SELECT ON TABLE FOREIGN_DATA_WRAPPERS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW FOREIGN_SERVER_OPTIONS AS
    SELECT FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME,
           OPTION_NAME, OPTION_VALUE
    FROM DEFINITION_SCHEMA.FOREIGN_SERVER_OPTIONS
    WHERE ( FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME )
       IN ( SELECT FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME
            FROM INFORMATION_SCHEMA.FOREIGN_SERVERS ) ;

GRANT SELECT ON TABLE FOREIGN_SERVER_OPTIONS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW FOREIGN_SERVERS AS
    SELECT FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME,
           FOREIGN_DATA_WRAPPER_CATALOG, FOREIGN_DATA_WRAPPER_NAME,
           FOREIGN_SERVER_TYPE, FOREIGN_SERVER_VERSION,
           AUTHORIZATION_IDENTIFIER
    FROM DEFINITION_SCHEMA.FOREIGN_SERVERS FS
    WHERE ( FS.FOREIGN_SERVER_CATALOG, '', FS.FOREIGN_SERVER_NAME )
       IN ( SELECT UP.OBJECT_CATALOG, UP.OBJECT_SCHEMA, UP.OBJECT_NAME
            FROM DEFINITION_SCHEMA.USAGE_PRIVILEGES AS UP
            WHERE ( UP.GRANTEE IN
                    ( 'PUBLIC', CURRENT_USER )
                 OR
                    UP.GRANTEE IN
                    ( SELECT ROLE_NAME
                      FROM ENABLED_ROLES ) ) )
      AND
          FS.FOREIGN_SERVER_CATALOG
        = ( SELECT CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME ) ;

GRANT SELECT ON TABLE FOREIGN_SERVERS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW FOREIGN_TABLE_OPTIONS AS
    SELECT FOREIGN_TABLE_CATALOG, FOREIGN_TABLE_SCHEMA, FOREIGN_TABLE_NAME,
           OPTION_NAME, OPTION_VALUE
    FROM DEFINITION_SCHEMA.FOREIGN_TABLE_OPTIONS
    WHERE ( FOREIGN_TABLE_CATALOG, FOREIGN_TABLE_SCHEMA, FOREIGN_TABLE_NAME ) IN
          ( SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
            FROM DEFINITION_SCHEMA.TABLE_PRIVILEGES
            WHERE GRANTEE IN
                  ( 'PUBLIC', CURRENT_USER )
          UNION
          SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
          FROM DEFINITION_SCHEMA.COLUMN_PRIVILEGES
          WHERE GRANTEE IN
                ( 'PUBLIC', CURRENT_USER ) )
      AND
          FOREIGN_TABLE_CATALOG
        = ( SELECT CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME ) ;

GRANT SELECT ON TABLE FOREIGN_TABLE_OPTIONS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW FOREIGN_TABLES AS
    SELECT FOREIGN_TABLE_CATALOG, FOREIGN_TABLE_SCHEMA, FOREIGN_TABLE_NAME,
           FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME
    FROM DEFINITION_SCHEMA.FOREIGN_TABLES
    WHERE ( FOREIGN_TABLE_CATALOG, FOREIGN_TABLE_SCHEMA, FOREIGN_TABLE_NAME ) IN
          ( SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
            FROM DEFINITION_SCHEMA.TABLE_PRIVILEGES
            WHERE GRANTEE IN
                  ( 'PUBLIC', CURRENT_USER )
          UNION
            SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
            FROM DEFINITION_SCHEMA.COLUMN_PRIVILEGES
            WHERE GRANTEE IN
                  ( 'PUBLIC', CURRENT_USER ) )
      AND
          FOREIGN_TABLE_CATALOG
        = ( SELECT CATALOG_NAME
            FROM INFORMATION_SCHEMA_CATALOG_NAME ) ;

GRANT SELECT ON TABLE FOREIGN_TABLES
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW ROUTINE_MAPPING_OPTIONS AS
    SELECT RMO.ROUTINE_MAPPING_NAME, RMO.OPTION_NAME, RMO.OPTION_VALUE
    FROM DEFINITION_SCHEMA.ROUTINE_MAPPING_OPTIONS AS RMO
    WHERE RMO.ROUTINE_MAPPING_NAME IN
          ( SELECT RM.ROUTINE_MAPPING_NAME
            FROM INFORMATION_SCHEMA.ROUTINE_MAPPINGS AS RM );

GRANT SELECT ON TABLE ROUTINE_MAPPING_OPTIONS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW ROUTINE_MAPPINGS AS
    SELECT RM.ROUTINE_MAPPING_NAME, RM.SPECIFIC_CATALOG,
           RM.SPECIFIC_SCHEMA, RM.SPECIFIC_NAME,
           RM.FOREIGN_SERVER_CATALOG, RM.FOREIGN_SERVER_NAME
    FROM DEFINITION_SCHEMA.ROUTINE_MAPPINGS AS RM
    WHERE ( RM.FOREIGN_SERVER_CATALOG, RM.FOREIGN_SERVER_NAME ) IN
          ( SELECT FS.FOREIGN_SERVER_CATALOG, FS.FOREIGN_SERVER_NAME
            FROM INFORMATION_SCHEMA.FOREIGN_SERVERS AS FS );

GRANT SELECT ON TABLE ROUTINE_MAPPINGS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW USER_MAPPING_OPTIONS AS
    SELECT UMO.AUTHORIZATION_IDENTIFIER,
           UMO.FOREIGN_SERVER_CATALOG, UMO.FOREIGN_SERVER_NAME,
           UMO.OPTION_NAME, UMO.OPTION_VALUE
    FROM DEFINITION_SCHEMA.USER_MAPPING_OPTIONS AS UMO
    WHERE ( UMO.AUTHORIZATION_IDENTIFIER,
           UMO.FOREIGN_SERVER_CATALOG, UMO.FOREIGN_SERVER_NAME ) IN
          ( SELECT UM.AUTHORIZATION_IDENTIFIER,
           UM.FOREIGN_SERVER_CATALOG, UM.FOREIGN_SERVER_NAME
            FROM INFORMATION_SCHEMA.USER_MAPPINGS AS UM );

GRANT SELECT ON TABLE USER_MAPPING_OPTIONS
    TO PUBLIC WITH GRANT OPTION;

  
CREATE VIEW USER_MAPPINGS AS
    SELECT UM.AUTHORIZATION_IDENTIFIER,
           UM.FOREIGN_SERVER_CATALOG, UM.FOREIGN_SERVER_NAME
    FROM DEFINITION_SCHEMA.USER_MAPPINGS AS UM
    WHERE ( UM.FOREIGN_SERVER_CATALOG, UM.FOREIGN_SERVER_NAME )
          IN ( SELECT FOREIGN_SERVER_CATALOG, FOREIGN_SERVER_NAME
            FROM INFORMATION_SCHEMA.FOREIGN_SERVERS );

GRANT SELECT ON TABLE USER_MAPPINGS
    TO PUBLIC WITH GRANT OPTION;

  